### ISSUE TITLE
[request] script

### ISSUE THREAD

**Issue by kittenvr** [Naezr/ShyFox#1]
could you make a script to automaticly do the steps for windows?

**Comment by Naezr** [comment]
I realize that the installation may seem too complicated for many people. But it is hardly possible to install extensions and import settings into them using a third-party script. Same with fx-autoconfig. If the developer of fx-autoconfig himself did not make an installer, then there are reasons for that. The only thing I can do is to detail the installation process in README. I actually wrote it very quickly without going into detail, so there's a lot more work to do

**Comment by kittenvr** [comment]
> I realize that the installation may seem too complicated for many people. But it is hardly possible to install extensions and import settings into them using a third-party script. Same with fx-autoconfig. If the developer of fx-autoconfig himself did not make an installer, then there are reasons for that. The only thing I can do is to detail the installation process in README. I actually wrote it very quickly without going into detail, so there's a lot more work to do


It's in russianhttps://private-user-images.githubusercontent.com/95460152/300262213-e392cad6-e975-4db1-9252-3d747ee0979f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MzQzMzgsIm5iZiI6MTcwNjUzNDAzOCwicGF0aCI6Ii85NTQ2MDE1Mi8zMDAyNjIyMTMtZTM5MmNhZDYtZTk3NS00ZGIxLTkyNTItM2Q3NDdlZTA5NzlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDEzMTM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkN2M3N2EyODAzNTg1YTdmNjZmNWVmYTQ2Y2U4ODBhYTdhYmMzYmM3ZDlkNjI0MDcyMDg5MDYwZDM0OTdkZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bMdNhpLPUxoIx-RPOZgsmzefiMG5s2q7wUHHbmcdkI8

**Comment by JanLunge** [comment]
here is the preview in english if you need that. you can also use this in the README if that seems necessary. the screenshot was helpful enough for me while its just a step to verify the fx-autoconfig installation
![Screenshot 2024-01-30 at 16 03 24](https://github.com/Naezr/ShyFox/assets/24433286/19cefc9a-4ecc-478a-8976-64e1d19caaf4)

**Comment by Naezr** [comment]
> It's in russian

In any case, you didn't have a userScripts section before.

**Comment by Naezr** [comment]
https://github.com/Naezr/ShyFox/discussions/46
