### ISSUE TITLE
How to increase size of invisible hover targets for sidebar, navbar, and toolbar?

### ISSUE THREAD

**Issue by careb0t** [Naezr/ShyFox#100]
How can we increase the size of the invisible hover targets? I looked into `shy-sidebar.css` and found this block below, but changing the width of it doesn't make the hover area to open the sidebar any larger. This is especially annoying for me using a tiling window manager on Linux where if the left size of the Firefox window is in the middle of the screen, I often miss the hover target entirely and end up hovering on whatever window is open to the left because the hover target area is too narrow.

![image](https://github.com/user-attachments/assets/32f46124-69a6-4a1a-9978-d5d51b7ac97c)

**Comment by Naezr** [comment]
https://github.com/Naezr/ShyFox/blob/324088ac06a5b962408875cf2a94275a855c8aa4/chrome/ShyFox/shy-variables.css#L48-L53
