### ISSUE TITLE
Right click menu transparent

### ISSUE THREAD

**Issue by TickyTacky999** [Naezr/ShyFox#101]
![image](https://github.com/user-attachments/assets/b1a1ef86-c6fe-4226-9cc6-2216e1217b5e)
When you click bookmarks and stuff or right click extensions, this is what it shows.
It used to show: 
![image](https://github.com/user-attachments/assets/29367cab-45ec-4c22-929f-c9f38a9c1d86)
Any way to fix this?

Thanks for your amazing work!

**Comment by TickyTacky999** [comment]
Another issue I noticed is that everytime when I restart the browser sideberry opens closed. Shall I make a new issue with that or is this known?

**Comment by Naezr** [comment]
What kind of color theme are you using? Adaptive Tab Bar Color? Firefox Color? System Theme - auto?

About the sidebar auto-opening. It has nothing to do with the theme itself. However, I'm trying to find a solution. Search the internet yourself for something like "Firefox auto-open sidebar in new windows" if interested.

**Comment by TickyTacky999** [comment]
I am using system theme auto (Tried dark as well) & I am using adaptive tab color.
I 've played around a little but, but when turning off adaptive tab color the issue is gone. It doesn't matter which theme I use it has the same issue.

Thank you so much for your response!

**Comment by Naezr** [comment]
Did you set the same color for the tab bar background and for the toolbar background in Adaptive Tab Bar Color settings. There is a note in the README about it

**Comment by Naezr** [comment]
When using Adaptive Tab Bar Color there is no difference between themes you use in Firefox settings. This extension overrides this at all. Same with Firefox Color. If your context menu is transparent, there is a 70% chance that the problem is caused by the wrong configured color scheme, not by ShyFox itself.

**Comment by TickyTacky999** [comment]
I followed the settings you gave for ATBC
![image](https://github.com/user-attachments/assets/5fe6fcef-2139-4b8f-948b-efed3aee000c)

**Comment by TickyTacky999** [comment]
I actually removed ATBC, reinstalled it and put the settings back in and the issue seems to be gone now. Not sure how that happened. 

Thank you sooo much for helping me out, ur amazing!

**Comment by TickyTacky999** [comment]
Just a quick question, I've tried to fix it but I can't seem to find out where the issue is.
But if I click close all tabs: 
![image](https://github.com/user-attachments/assets/d5278c75-e45d-45e7-bd32-8f06f66b7980)
Instead of closing it all, it will always open a new tab. In the older versions it would jump to another active tab in another panel. But now I can't seem to completely shutdown/unload a panel.

**Comment by Naezr** [comment]
Right click on blank space > configure panel. You need turn off this setting for each space
![изображение](https://github.com/user-attachments/assets/f9f50fb7-6927-4e25-9868-0a328da74a4a)

**Comment by TickyTacky999** [comment]
Ur a legend. And I am blind.

Thank you so much boss!
