### ISSUE TITLE
Sidebar is a bit strange

### ISSUE THREAD

**Issue by synqqrawr** [Naezr/ShyFox#102]
When dragging around tabs in sidebery, it doesn't move to the right spot.

https://files.catbox.moe/0mvsga.mp4

**Comment by Naezr** [comment]
It seems that this site is not available in my country. You can upload the video directly to GitHub. Just drag it into the text input field

**Comment by synqqrawr** [comment]
oops, mybad but it is over 20mb so i cant here. which site would work?

**Comment by Naezr** [comment]
Imgur works fine for me

**Comment by synqqrawr** [comment]
imgur doesn't allow 60s+ vids.

https://cdn.discordapp.com/attachments/1249495838447898735/1264102357701230654/2024-07-20_13-30-53.mp4?ex=669ca68f&is=669b550f&hm=333e39ff6cfd7586d4dab691306e12b92797d507fd34d5c965a86760ac78ee24&

does discordwork?

**Comment by Naezr** [comment]
Discord works fine. This bug is already fixed 
https://github.com/Naezr/ShyFox/commit/324088ac06a5b962408875cf2a94275a855c8aa4#diff-09c9ae68739e06a429c9a20b5eaab3d2467168bd5eea4854e403d77edda9dc23

**Comment by synqqrawr** [comment]
oops my bad, i should've updated before trying
