### ISSUE TITLE
Toolbar can't be hovered under certain circumstances.

### ISSUE THREAD

**Issue by Neubulae** [Naezr/ShyFox#104]
If I manually set `layout.css.devPixelsPerPx` to number less than its default value(it defaults to -1, which means it's been automatically determined by system DPI. On my setup it's equivalent to 2), toolbar can't be hovered, presumably being covered by slide bar.

**Comment by Naezr** [comment]
[Запись экрана от 2024-07-20 20-16-52.webm](https://github.com/user-attachments/assets/de242923-d53d-496f-a886-a9474cb9ad01)
What exactly do you mean by “toolbar can't be hovered”? It looks silly to me, the scale is too large. But it works.

**Comment by Neubulae** [comment]
> 2024-07-20.20-16-52.webm
> 
> What exactly do you mean by “toolbar can't be hovered”? It looks silly to me, the scale is too large. But it works.

Try setting it to 0.8 or 0.75 to see what I mean I guess?

For sake of clarity here are the details.
I have a 2560x1440 display, obviously that would make everything look awkwardly small under 1x DPI. As such I changed my system-wide setting to 2x DPI. Now everything looks OK-ishly large, but for Firefox I want it to be downscaled.
Firefox's setting only scales for text elements. For its own UI elements it won't work, things would look off. So I quickly Googled a solution that suggests changing `layout.css.devPixelsPerPx` to a value lower than your system setting, in this case I changed to `1.5`, Since 1.5 < 2.
Now if I hover above where the toolbox should be, it won't show up. But a number bigger or equal to 2 works as it should.

**Comment by Naezr** [comment]
[Запись экрана от 2024-07-20 21-57-21.webm](https://github.com/user-attachments/assets/7fd60094-f86b-4b49-9c05-fb0ad30de28f)

**Comment by Naezr** [comment]
Even at 0.1 I have everything working, considering it's impossible to see anything properly there. Could you show a video of what exactly is going on for you?

**Comment by Neubulae** [comment]
https://github.com/user-attachments/assets/7aa9b82a-d188-4060-afc7-50902b11559f

**Comment by Neubulae** [comment]
https://github.com/user-attachments/assets/ceeb2cfc-9dc8-4e71-a4b2-c372f795a5c8

I'm under Wayland btw, I forgot to say that

**Comment by Naezr** [comment]
Either I'm missing something, or you forgot to mention that you're doing it in fullscreen mode. The hitbox for hovering in fullscreen is 1px. Most likely this kind of scaling is bad for that 1px. Increase this value for f11 fullscreen 

https://github.com/Naezr/ShyFox/blob/324088ac06a5b962408875cf2a94275a855c8aa4/chrome/ShyFox/shy-variables.css#L48-L53

**Comment by Neubulae** [comment]
Thx, checking out

**Comment by Neubulae** [comment]
Making it 2px worked, thx!
