### ISSUE TITLE
Can't hide toolbar while also hiding side bar

### ISSUE THREAD

**Issue by duckworx** [Naezr/ShyFox#112]
When i try to hide the side bar while also hiding the toolbar the toolbar just pops right back out

**Comment by Naezr** [comment]
Userchrome Toggle settings > "allow multiple styles to be active together" > APPLY CHANGES

**Comment by duckworx** [comment]
> Userchrome Toggle settings > "allow multiple styles to be active together" > APPLY CHANGES

u make me look silly :3
