### ISSUE TITLE
[Request] make context menu nicer, like edge-frfox

### ISSUE THREAD

**Issue by Arcticn** [Naezr/ShyFox#115]
Thanks for your work! This theme is incredibly great.
But the ugly context menu and bookmark menu destroyed it!

I think edge-frfox has made it look nice, can we enhance ShyFox based on it?
https://github.com/bmFtZQ/edge-frfox

![图片](https://github.com/user-attachments/assets/914a0e1c-c41c-43a7-a420-146892fc442f)
![图片](https://github.com/user-attachments/assets/5d73560f-5414-4ebb-8ee5-ad482ab0e804)

**Comment by Naezr** [comment]
> the ugly context menu and bookmark menu

It's not ugly, I like it. But I can add an option to make the context menu larger

Uploaded the experiment to the nightly branch. You need to set `shyfox.larger.context.menu` to `true` in `about:config` to enable this

![изображение](https://github.com/user-attachments/assets/e2a474f3-d760-42ac-82d0-cd6c22e40a67)
Is it looks good for you?

**Comment by Arcticn** [comment]
Love it, that's pretty good!
Thanks a lot!
