### ISSUE TITLE
[Request] floating elements always visible

### ISSUE THREAD

**Issue by claymorwan** [Naezr/ShyFox#116]
It would be nice to have the option to have the floating elements to always show. For example if I want the navbar to be floating like it is when hovering in hidden, same for the sidebar and toolbar. Each can be toggled independantly :3 (please)

**Comment by Naezr** [comment]
First of all, Userchrome Toggle doesn't have enough toggles for all that. Even though I took over the development of this extension and am rewriting it from scratch right now, I don't intend to add more than six toggles. That would be overkill.

Secondly, what's the point? Why would you want to do that? What's wrong with the normal panel mode? When the hidden panel slides out, it overlaps the content. Why would you want to overlap content all the time?

**Comment by claymorwan** [comment]
I just thought that having the navbar always showing but floating would look gud, but dw if u can't or don't wanna it's fwine, it's still a really gud theme ^w^

**Comment by Naezr** [comment]
> if u can't or don't wanna

I think it's both. Implementation would likely prove too difficult relative to utility and demand.

> it's still a really gud theme ^w^

Thanks, I'm glad you liked it
