### ISSUE TITLE
remove "open sidebar" popup

### ISSUE THREAD

**Issue by zaeemali272** [Naezr/ShyFox#119]
Hello!!
is there a way to remove the open sidebar popup its kinda annoying, whenever a small window opens like for authentication it is there.

&&

cant i just use the extension from the start. when i open a new window i have to click on the extension to use it.

![Screenshot from 2024-08-03 17-24-05](https://github.com/user-attachments/assets/9b42b912-af69-4f62-a384-ca83e38765fd)
THANK YOU :)

**Comment by Naezr** [comment]
> is there a way to remove the open sidebar popup its kinda annoying, whenever a small window opens like for authentication it is there.

As I remember, this has already been fixed. Are you sure you have updated to the latest version of ShyFox?

> cant i just use the extension from the start. when i open a new window i have to click on the extension to use it.

I don't know why, but that's how it works for me, I don't have to open the sidebar myself. My Firefox profile is pretty old, so it's possible that I still have some hidden setting enabled that was turned off in the default settings for newer versions of Firefox. I have no idea how to turn that on for the new clean Firefox, but I'll try to figure it out later.

Right now I'm busy developing a new version of Userchrome Toggle Extended.

**Comment by Naezr** [comment]
https://support.mozilla.org/en-US/questions/1342740

I don't know if this will help you, but it's the only thing I've found on the issue

https://github.com/Naezr/ShyFox/issues/92

**Comment by zaeemali272** [comment]
> https://support.mozilla.org/en-US/questions/1342740
> 
> I don't know if this will help you, but it's the only thing I've found on the issue
> 
> #92

Thanks bro
removing the **xulstore.json** file from the **profile folder** fixed it

**Comment by Naezr** [comment]
What about "Open sidebar!" popup?

**Comment by Arcticn** [comment]
It works! But still get "Open sidebar!" in new private window, is it correct?

**Comment by Naezr** [comment]
Yes, sidebar cannot be opened automatically in private windows. Firefox security limitations
