### ISSUE TITLE
Two popup menus.

### ISSUE THREAD

**Issue by RustyElbow** [Naezr/ShyFox#124]
Hey, I'm getting this bug with the context menus... is there any soulution?

Thank you :)

![Screenshot 2024-08-06 220310](https://github.com/user-attachments/assets/425e4f78-f379-400e-9c1d-b6c8a63a6381)

**Comment by Naezr** [comment]
![image](https://github.com/user-attachments/assets/59de57d5-5e98-4b34-9977-43e0cab89321)
Try native Sidebery menu

**Comment by Naezr** [comment]
No. This is the first time I've seen it
