### ISSUE TITLE
Floorp Support

### ISSUE THREAD

**Issue by Mojas84** [Naezr/ShyFox#128]
Support floorp we can do it?? Floorp is better as firefox.

**Comment by Naezr** [comment]
Floorp is too overpowered for my taste. It has a lot of different features and customizations to consider, but which are not entirely clear how to use in the context of ShyFox. Also, half of the css selectors in Floorp just didn't work the last time I tried to get ShyFox in there. Firefox is many times easier in this regard. I'll probably look into it someday, but I'm not really interested

**Comment by Mojas84** [comment]
> Floorp is too overpowered for my taste. It has a lot of different features and customizations to consider, but which are not entirely clear how to use in the context of ShyFox. Also, half of the css selectors in Floorp just didn't work the last time I tried to get ShyFox in there. Firefox is many times easier in this regard. I'll probably look into it someday, but I'm not really interested

OK THX
