### ISSUE TITLE
Support native vertial tab as alternative option

### ISSUE THREAD

**Issue by ilsubyeega** [Naezr/ShyFox#129]
It appears that sidebery is not being actively maintained at the moment. Two recent issues I've encountered seem to illustrate this situation.

Given this situation, although I question the timing, I think it would be a good idea to add an option to choose the [browser's native vertical tabbing feature](https://imgur.com/lfFRL73) instead of sidebery.

Of course, sidebery will always be a great extension, but providing users with multiple choices might be a better approach. This would allow users to choose the option that best suits their needs.

**Comment by Naezr** [comment]
Already planned. Most likely to appear in _ShyFox 4.0_

**Comment by Naezr** [comment]
4.0 is in development
