### ISSUE TITLE
Shyfox feels laggy/slow

### ISSUE THREAD

**Issue by KAGEYAM4** [Naezr/ShyFox#135]
In the video below left is shyfox in a new firefox profile, right is my different firefox setup.  In the video you can see the shadow behind the selected context menu item as i move my mouse over them. In shyfox it feels laggy. This is the same in floating addressbar which was improved when i turned off floating search off, but it was still laggy with floating addressbar which gets improved when i turn off floating addressbar.

https://github.com/user-attachments/assets/f9e08c43-7002-4bdd-bc2c-d70aa6ef7f98

Is there some kind of custom implementation being used for contex menu ?

**Comment by Naezr** [comment]
> Is there some kind of custom implementation being used for contex menu ?

All changes to the context menu:

Color:
https://github.com/Naezr/ShyFox/blob/73a25ebd70f5c02fe61dc96467550b8b8f146d3b/chrome/ShyFox/shy-global.css#L290C1-L339C1

Size:
https://github.com/Naezr/ShyFox/blob/73a25ebd70f5c02fe61dc96467550b8b8f146d3b/chrome/ShyFox/shy-compact.css#L5C1-L41C119

Space for icons:
https://github.com/Naezr/ShyFox/blob/73a25ebd70f5c02fe61dc96467550b8b8f146d3b/chrome/ShyFox/shy-icons.css#L289C1-L299C65

-----------------------------------

ShyFox is really complicated. Version 4.0 will be even more complicated (see the announcement in the discussion tab). But there’s no other way to do it. Many complex css selectors can be simplified by injecting a custom script into Firefox. Maybe someday ShyFox will turn into a full-fledged fork of Firefox or something. However, now there are quite complicated selectors that can possibly cause lags. My laptop is not the most powerful and everything works well for me so I don't know really

**Comment by KAGEYAM4** [comment]
v4.0 gonna be awesome. Thanks for you work.


Not sure if it will help or not, but i was using https://github.com/black7375/Firefox-UI-Fix before shyfox. It also modifies context menu but not that heavily, here's all of its options -> https://github.com/black7375/Firefox-UI-Fix/wiki/Options.

**Comment by KAGEYAM4** [comment]
@Naezr  i also noticed lag/glitch animation when scrolling page.

Steps to reproduce ->
1. Go to some site which has large vertical content.
2. Perform large swipe  using touchpad.
3. Animation would lag.

**Comment by KAGEYAM4** [comment]
@Naezr  wanted to share another behaviour where lags increases ->

Toggling - Style2, Style3, Style4 creates lag.  Style1 dosen't create lag

https://github.com/user-attachments/assets/5877f277-55cf-4e53-bbfc-e994d68d8909
