### ISSUE TITLE
System button text displacement

### ISSUE THREAD

**Issue by User094573** [Naezr/ShyFox#139]
I'm using EndeavourOS, xfce4 desktop.

After installing ShyFox's files into my profile folder I've noticed that somehow placement of a text on a system panel button seems a bit off. Here's a screenshot.

![shyfox-glitch](https://github.com/user-attachments/assets/af312df7-b0f9-4129-905d-d6c565e087fd)

**Comment by Naezr** [comment]
This is a problem with one of the invisible characters in Userchrome Toggle. It appears to be increasing the height of the string. This symbol should be replaced with another one, but you will have to update the extension and ShyFox itself. But this will break everything, as the extension will update automatically, but the theme will stay the same. People won't be able to hide their sidebar and will be forced to update

**Comment by Naezr** [comment]
The extension has been updated, so has ShyFox. Reset the extension settings after the update to get the new symbol
