### ISSUE TITLE
Title Bar Buttons and Drop Down Menu Broken by Update

### ISSUE THREAD

**Issue by C-Furber** [Naezr/ShyFox#15]
After the newest Firefox update, the title bar buttons have (maybe?) one pixel at most, of usage. Also, the dropdown menu containing the hamburger menu and extensions is completely gone. Screw firefox updates ;-;

**Comment by Naezr** [comment]
Need more details. Platform, browser version, screenshots or videos. It's not clear right now

**Comment by C-Furber** [comment]
Firefox ver. 123.0, Windows 10

Video too large for github, here's the yt link:
https://youtu.be/KdOM-Tioqws

**Comment by Naezr** [comment]
Checked on Windows 11 with a clean profile, can't replicate. I'll go download windows 10 for the tests

**Comment by C-Furber** [comment]
Hey, you were right, I had to perform a clean reinstall of Firefox and it's good now. However, weird thing, when I open a new window, userchrome toggle doesn't automatically hide the sidebar. Try dragging a window from the sidebar or right-clicking on a window on sidebery and clicking "Move to" -> "New window", and the sidebar just remains seen until I turn it off and back on, any tips? (This is on a clean profile as well :/ )

Firefox ver 123.0, Windows 10
