### ISSUE TITLE
Sidebery `Tabs preview` shows behind sidebery when floating Sidebar with default settings.

### ISSUE THREAD

**Issue by KAGEYAM4** [Naezr/ShyFox#152]
**Note** -  this can be totally fixed by user by changing settings provided by Sidebery, but i wanted to know if there was a way to make dynamic. But then again this tweaking in sideberyy will be on very rare occasions ( i.e when sidebar size is changed by user using css )

In sidebery settings, under `Tabs preview` enable `Show tab preview on mouse hover` and set `Preview mode` to `popup in page` and also set `sidebar side` to `left`. The preview will be shows behind sidebery.

**Comment by Naezr** [comment]
These previews can be styled, but this cannot be linked to the title prefix. Since these previews are on the page and not in the interface, they are not linked to the :root element of the main window
