### ISSUE TITLE
New zero width char for hiding sidebar

### ISSUE THREAD

**Issue by thangisme** [Naezr/ShyFox#153]
I'm using waybar, the current char make it output in a newline like this: 
![image](https://github.com/user-attachments/assets/b099e09c-c98a-4ff6-a89b-8a4b6cb4859f)
![image](https://github.com/user-attachments/assets/d2c299af-c432-446d-8a9d-7bce4f69c273)
The other prefix in the addon don't cause the issue
![image](https://github.com/user-attachments/assets/989e23cd-c6c5-42f7-81ac-5707931237f3)

**Comment by Naezr** [comment]
https://github.com/Naezr/userchrome-toggle-extended-2/issues/7

**Comment by Naezr** [comment]
Are you sure you updated everything to the latest version?

**Comment by thangisme** [comment]
My bad
