### ISSUE TITLE
Use hidden mode by default

### ISSUE THREAD

**Issue by GMNDS** [Naezr/ShyFox#16]
Hello, thank you for this project.

  Using extended tabs by default breaks some extensions that can be opened as a tab, such as bitwarden, it would be interesting to use hidden mode by default, avoiding this:

![image](https://github.com/Naezr/ShyFox/assets/138012112/d129b191-77a9-459d-9056-44fd8a21388d)

**Comment by Naezr** [comment]
Fixed in 3.0, check it out
