### ISSUE TITLE
Weird bar on my homepage

### ISSUE THREAD

**Issue by rahul-muthu** [Naezr/ShyFox#160]
![image](https://github.com/user-attachments/assets/f4f7cc3c-e6f6-4bed-a1a0-40fd34b06079)

I have this weird bar on my home page, it stays even when I dock. It disappears after I open any other tab that is not the homepage. Just a visual/aesthetic bug, would like to fix it.

**Comment by Naezr** [comment]
![image](https://github.com/user-attachments/assets/19a6a576-f752-48d5-8962-758fcc145e66)
![image](https://github.com/user-attachments/assets/d144b7c3-24d4-4e4d-b4db-63f00fa3b14f)

**Comment by rahul-muthu** [comment]
Thank you so much
