### ISSUE TITLE
How to set toggle keybinds?

### ISSUE THREAD

**Issue by OfficialCRUGG** [Naezr/ShyFox#162]
You recommend setting a few certain keybinds for userchrome toggles:

![image](https://github.com/user-attachments/assets/5359565e-adc2-45c9-bef5-1e6ec73914b0)

But how do I actually set these? From what I've seen, I couldn't find any feature in Userchrome Toggle Extended to set these keybinds. And the defaults conflict with macOS keybinds, so these are currently unusable for me:

![image](https://github.com/user-attachments/assets/6bfaf951-d193-407a-a31e-0ab7573cbe21)

**Comment by Naezr** [comment]
There is actually a screenshot in the installation guide

**Comment by OfficialCRUGG** [comment]
Thanks, but where in the installation guide is a screenshot of that? I just went over it a few times and can't find it.

**Comment by Naezr** [comment]
Step 2 drop-down named "Configure Userchrome Toggle Extended"

**Comment by OfficialCRUGG** [comment]
Ah, I see. I didn't actually notice that these can be clicked.
