### ISSUE TITLE
On latest Nightly, hovering on Sidebar won't invoke it.

### ISSUE THREAD

**Issue by Neubulae** [Naezr/ShyFox#166]
The vertical bar for it also seemed missing. After some very speculative testing I suppose Firefox decided to leverage their own sidebar implementation by increasing their z-index.
I had to enable their native sidebar function to use Sidebery...
Or I increase Sidebery's `z-index` to `3`.
I do not know better but if that's a suitable fix I'd submit a pull request.

**Comment by Neubulae** [comment]
Just a quick screenshot to demonstrate what I'm talking about:

<details>
<summary>`z-index: 3`</summary>
![图片](https://github.com/user-attachments/assets/fa6153ae-ab3d-4a60-886d-5f3c14038946)
</details>


<details>
<summary>`z-index: 2`</summary>

![图片](https://github.com/user-attachments/assets/eced7691-e37f-43f1-9b80-1d1d42c35a72)

</details>

**Comment by Naezr** [comment]
ShyFox 3.8.1 is kind of stable right now. It runs on the latest stable Firefox. If Firefox updates and something breaks, I'll fix it. If you want the experience of using something unfinished, there is a ShyFox 4.0-alpha for Firefox Nightly.

**Comment by Neubulae** [comment]
> ShyFox 3.8.1 is kind of stable right now. It runs on the latest stable Firefox. If Firefox updates and something breaks, I'll fix it. If you want the experience of using something unfinished, there is a ShyFox 4.0-alpha for Firefox Nightly.

Ah OK, thx!
