### ISSUE TITLE
Bro the new update did this 

### ISSUE THREAD

**Issue by zaeemali272** [Naezr/ShyFox#169]
![image](https://github.com/user-attachments/assets/46d2e360-ebfe-4afe-bb3c-d84ef5ac9a0e)

this is in the hidden state

**Comment by Naezr** [comment]
What update are we talking about? I'm running Firefox 130.0.1 and everything works as it should.

**Comment by zaeemali272** [comment]
im using firefox nightly 132.0a1, its showing transparent background in toolbar and navbar, and just the background of sidebar even when hidden.

**Comment by Naezr** [comment]
fix uploaded
