### ISSUE TITLE
new-tab content occludes the search bar

### ISSUE THREAD

**Issue by ashkyn** [Naezr/ShyFox#174]
Hi!

Having an issue where new-tab occludes the search bar, looks like an issue with the padding/margin?

![image](https://github.com/user-attachments/assets/60cbfde1-66a0-477d-9612-2e46b8cbb317)

Any idea which class might be to blame?

**Comment by Naezr** [comment]
Right click on the empty space on the right > Bookmarks Toolbar > Any other mode than "show only on a new tab"

**Comment by ashkyn** [comment]
Thank you, that resolved it!
