### ISSUE TITLE
Sideberry tab panels unclickable when the sidebar is active

### ISSUE THREAD

**Issue by emorevival** [Naezr/ShyFox#177]
Hi, I'm new to debugging browser styles, I've been trying to figure out what's blocking these buttons from being clickable:
![image](https://github.com/user-attachments/assets/574e469f-5d9b-4c82-8890-0db0611216e7)

I noticed that if I click on the very bottom of the buttons they're clickable, and also right clicking on them opens two context menus (indicating that there's an element on top of them). I've tried changing their z-index but it didn't help. Maybe you'll know what that could be?

I'm using Firefox 131.0.2 (64-bit), on a Windows 10 machine.

**Comment by emorevival** [comment]
actually the search and new tab panel buttons are unclickable as well

**Comment by Naezr** [comment]
https://github.com/Naezr/ShyFox/issues/149

**Comment by emorevival** [comment]
ahh thanks, i searched the closed and open issues but this one doesn't have
the word panel in it. will try it in a bit and close this if it works

**Comment by emorevival** [comment]
that solves it. thanks
