### ISSUE TITLE
[Issue] Extensions popups isn't reachable

### ISSUE THREAD

**Issue by alr86** [Naezr/ShyFox#181]
### Issue:

Extension popups are not displaying correctly.  Instead of the expected content, a black popup appears.

### Example:

This issue was encountered with the "Smart Proxy" extension and its "Failed Requests" option. Clicking on the "Failed Requests" button resulted in a black popup instead of the expected list of failed requests.

#### Steps to Reproduce:
 1.  Install the "Smart Proxy" extension.
 2.  Add a wrong proxy and enable it.
 3.  Open a wabsite 
 4.  Click on the "Failed Requests" button in smart proxy extention menu.

**Comment by Naezr** [comment]
Any screenshots or something? I installed this extension and I don't have an "Failed Requests" button. Maybe it's the wrong extension, give me a link to it

**Comment by alr86** [comment]
Example extension: https://addons.mozilla.org/en-US/firefox/addon/smartproxy/

### Screenshots:
![image](https://github.com/user-attachments/assets/948432c6-b0f4-4b05-b80f-c842a27736e2)
![image](https://github.com/user-attachments/assets/7109819b-dc32-42ef-85c4-f08569fbe917)

**Comment by Naezr** [comment]
[Запись экрана от 2024-10-23 21-36-49.webm](https://github.com/user-attachments/assets/db652e37-f632-4be5-8c8f-1825e4fc9781)

Works great for me. Are there any additional details that would make a difference? Your system, version of Firefox, anything else?

**Comment by alr86** [comment]
### Update:
I think this issue is an extension issue and is not related to Firefox. So I will close this issue.
Thank you for paying attention! ❤️
