### ISSUE TITLE
Firefox update broke shyfox completely

### ISSUE THREAD

**Issue by TickyTacky999** [Naezr/ShyFox#185]
Does the firefox update broke Shyfox for other people as well or is it just me?

![image](https://github.com/user-attachments/assets/92247942-ba52-4322-9e8a-39702b8d1303)

**Comment by koeqaife** [comment]
I have the same problem

**Comment by Naezr** [comment]
What Firefox update broke everything? Are you using the most recent version of ShyFox?

**Comment by koeqaife** [comment]
I just reinstalled ShyFox and now almost everything is okay

**Comment by claymorwan** [comment]
I reinstalled it but still broken

**Comment by KAGEYAM4** [comment]
> I reinstalled it but still broken

for me its working. Delete the chrome folder and copy the one from this repo.

**Comment by darshan019** [comment]
> > I reinstalled it but still broken
> 
> for me its working. Delete the chrome folder and copy the one from this repo.

Did it, but the tabs panel is not closing even when it's not on focus. Other than that, many issues OP had were solved, how did you correct this?

**Comment by KAGEYAM4** [comment]
@darshan019 by tabs panel do you mean the Sidebery Panel in left? If yes, then i just noticed that its not hiding.

**Comment by darshan019** [comment]
@KAGEYAM4 Yup

**Comment by Naezr** [comment]
Reset Userchrome Toggle settings

**Comment by claymorwan** [comment]
Did all that but still broken

**Comment by KAGEYAM4** [comment]
> Reset Userchrome Toggle settings

Worked for me.

The only unrelated problem is that if i toggle more than the settings in the photo and don't restart firefox my-self after toggling one option --> firefox will crash.

![image](https://github.com/user-attachments/assets/70d7da32-0954-4344-8dae-9f42f579fb90)

**Comment by oskhen** [comment]
git pull, reinstalling, resetting userchrome settings. Now everything is working for me again. Cheers.

**Comment by TickyTacky999** [comment]
Sorry I was at work.
It broke

**Comment by TickyTacky999** [comment]
Sorry I was at work.
It broke

**Comment by darshan019** [comment]
It's working now just reinstalled userchrome extension

**Comment by claymorwan** [comment]
I keep doing all that but it's still broken wth
