### ISSUE TITLE
navbar, toolbar and some menu background are now transparent

### ISSUE THREAD

**Issue by CharlesGueunet** [Naezr/ShyFox#191]
This is a recent issue, that arose with the latest Firefox update to version 132.
I reproduced it using the master version of ShyFox.

Some UI element are transparent:
![image](https://github.com/user-attachments/assets/dbdf00a4-22da-4fe8-8a90-19da59e00b25)

When fully visible (not in hidden mode) the navbar and toolbar have transparent backgrounds which make them inconvenient to use. Their hidden version has no issue though.

I am using the default system dark theme for firefox, without any other theme related extension.

**Comment by Naezr** [comment]
just download the latest ShyFox, this is already fixed

**Comment by CharlesGueunet** [comment]
> just download the latest ShyFox, this is already fixed

on the master branch ? I am currently on the latest version

**Comment by Naezr** [comment]
Yeah, the main branch

**Comment by CharlesGueunet** [comment]
Strange, I am up to date, I have checked the profile used is the right one and I have restarted Firefox. 

Also, I tried Firefox colors as suggested in the readme and it suffers the same issue.

**Comment by Naezr** [comment]
By up to date, do you mean you downloaded and installed the files from the main branch right now?

**Comment by CharlesGueunet** [comment]
> By up to date, do you mean you downloaded and installed the files from the main branch right now?
Yes, I unzipped the folder and put content of the `chrome` folder into the right location in my profile, then restarted firefox completely.

**Comment by Naezr** [comment]
I'm 99% sure that the latest version of ShyFox works correctly on Firefox 132.0.1. Are you sure you put the files in the right place?

**Comment by CharlesGueunet** [comment]
You are right, I updated my ESR profile, but not the one of my main browser ...

Sorry for the noise, this works as expected !
