### ISSUE TITLE
Panels to be hidden by setting

### ISSUE THREAD

**Issue by leakspin** [Naezr/ShyFox#20]
For me, having three panels is perfect, but I would like to have a configuration for having panels hidden by default. I don't usually use the right side panel and fills that bit of space that makes some websites to change from desktop to mobile view, so I need to hide it.
But I have the browser in three different screens, so I would have to configure UserChrome toggles every time I launch the browser in every window (and in every new window that I open).

So what I propose is to have some sort of setting for having panels hidden by default.

Also, thanks a lot for this theme! I really love it!

**Comment by Naezr** [comment]
Practically unrealizable on the userChrome.css side, but it's probably possible to do it on the userChrome Toggle extension side. It's possible that I'll look into improving userChrome Toggle at some point, but right now I don't have the knowledge to do so.

**Comment by Naezr** [comment]
https://github.com/Naezr/userchrome-toggle-extended/issues/2
