### ISSUE TITLE
How to remove this part ?

### ISSUE THREAD

**Issue by alienzj** [Naezr/ShyFox#216]
Hi @Naezr 

Thank you for the awesome Firefox configuration!

Could you please tell me how to remove the part shown in the figure below?

![image](https://github.com/user-attachments/assets/14e47b92-6e62-41a1-9a5b-2740775bfac9)

**Comment by Naezr** [comment]
Set `sidebar.revamp` to false in about:config

**Comment by alienzj** [comment]
Solved.
Thanks so much :)
