### ISSUE TITLE
Is there any way to get rid of the firefox logo?

### ISSUE THREAD

**Issue by venkeyu** [Naezr/ShyFox#218]
I really want to get rid of the Firefox logo whenever I open a new tab. It's bothering me and I just really want to take it out. Is there anyway to get rid of it?
![image](https://github.com/user-attachments/assets/787a1074-4a67-4d3d-abd3-d04b98a41efb)

**Comment by Akira-uestc** [comment]
modify ShyFox/chrome/ShyFox/content/shy-new-tab.css

```diff
@@ -96,7 +96,7 @@ Styles for new tab
       background-color: var(--tr-col) !important;
       backdrop-filter: blur(var(--blur-radius));
     }
-    .logo-and-wordmark {display: flex !important;}
+    .logo-and-wordmark {display: none !important;}
   }
   
   @media (height <= 700px) {
@@ -125,8 +125,6 @@ Styles for new tab
   main{
     margin-top: 15% !important;
     height: 50%;
-    background-color: var(--tr-col);
-    border-radius: var(--giant-rounding);
   }
```

**Comment by venkeyu** [comment]
changing 
`.logo-and-wordmark {display: flex !important;}`
into
`.logo-and-wordmark {display: none !important;}`
didn't get rid of the logo and wordmark for me

**Comment by venkeyu** [comment]
nevermind i fixed it. for some reason it worked perfectly when i tried it on my pc rather than my laptop. in order to change it to how i wanted it to i had to change 
 ```
 @media (height <= 700px) {
    .search-wrapper {display: none !important;}
    .outer-wrapper > main {margin-top: 0px !important;}
  }
```
only downside to using this rather than the code provided is that it gets rid of the search bar in the middle of the screen.
