### ISSUE TITLE
Sideberry imports

### ISSUE THREAD

**Issue by Dotdk** [Naezr/ShyFox#22]
There is something wrong when try to import 3.0 theme to sideberry there is nothing imported when trying 
Took the file from the other version and its working and it looking better

**Comment by Dotdk** [comment]
Maby its the settings i cant import it in the 3.0 version

**Comment by Naezr** [comment]
Already wrote about this in another issue, just duplicating it: 

 When importing styles, Sidebery does not delete the old style, but inserts the new one after the old one. To make the ShyFox style for Sidebery work, go to the Style editor page in Sidebery settings and delete everything from the text box on the right. Then re-import the file from ShyFox.

**Comment by Dotdk** [comment]
Oh im sorry dident read the other ones il found out u can just mark this one as compleated
