### ISSUE TITLE
How to get the big icons in the sidebery

### ISSUE THREAD

**Issue by Autonvilkku** [Naezr/ShyFox#221]
i can't get my sidebery to look like in the images
![image](https://github.com/user-attachments/assets/0cedf74f-a3f4-4422-bbd8-6681469d0c3e)

**Comment by Autonvilkku** [comment]
that is how it looks for me

**Comment by Burhanverse** [comment]
You'll have to pin the tabs to make it big like `card style`

**Comment by Autonvilkku** [comment]
### Thanks 
# 👍
