### ISSUE TITLE
Homepage shortcut looks broken

### ISSUE THREAD

**Issue by anoshione** [Naezr/ShyFox#23]
![image](https://github.com/Naezr/ShyFox/assets/81085871/a0ea4744-9bce-4071-aed3-bc4f334bf02d)

homepage shortcut looks like this, after i installed the recent update.

at first i thought maybe one of my extension is causing this, then i fresh installed firefox with only sidebery and userchrome toggle extension, still it looks like this.

**Comment by Naezr** [comment]
They don't look broken, they are really broken. I don't know what this is related to, but I'll try to reproduce and fix it.

Also, it seems I'd need to work on the colors in the default theme, without the Adaptive Tab Bar Color extension. Right now it doesn't look solid

**Comment by Naezr** [comment]
Upgraded to Firefox 124 and saw the same thing

**Comment by Naezr** [comment]
A quick fix has already been uploaded. It doesn't look exactly the same as before, but it's ok

**Comment by anoshione** [comment]
I wanted a dark bordered theme ,with light themed website. with adaptive tab bar i cant do that or i dont know how to, thats why i use a simple theme from store instead of adaptive color.

And as always thank you for the theme and quick responses to the issues.
