### ISSUE TITLE
side bar issue 

### ISSUE THREAD

**Issue by Dotdk** [Naezr/ShyFox#24]
is there eny reson i cant place enything under the expansion icon all i try to put in the bar drops down on the middle 
![image](https://github.com/Naezr/ShyFox/assets/6298561/3630f601-7e1c-4fac-b7a9-d5482fe35062)

**Comment by Naezr** [comment]
Add Flexible space there. Then the buttons above it will be at the top, and the buttons below it will be at the bottom in the visible state. In the hidden state flexible space will become a separator

![image](https://github.com/Naezr/ShyFox/assets/95460152/86ac9232-7c6d-4ef8-9319-c0d4c2b7fe80)   ![image](https://github.com/Naezr/ShyFox/assets/95460152/1bdb9163-f8c9-4114-8937-b5a43205b4d8)  ![image](https://github.com/Naezr/ShyFox/assets/95460152/6d2916bd-4911-414c-b76d-9b859f79e978)  ![image](https://github.com/Naezr/ShyFox/assets/95460152/e864f981-acf6-432a-a322-ebf743f0562d)

**Comment by Dotdk** [comment]
oh thx alot dident know i could do that love the amasing theme u have maked for firefox
