### ISSUE TITLE
Sidebery tree structure doesn't work + how to delete window controls

### ISSUE THREAD

**Issue by niksingh710** [Naezr/ShyFox#25]
Firstly Wow.
I was skeptical to switch to version 3.0 
but today got the time to switch and man you nailed it.
Like this is awesome. 🎊

Everything is fine and I love it.
Just is it possible to have Sideberry Tree like structure as earlier it used to have?

**Comment by niksingh710** [comment]
also how to hide that close button?

**Comment by Naezr** [comment]
Can you be more detailed and preferably with screenshots? I don't understand anything, what exactly is the close button, what is the tree structure?

**Comment by niksingh710** [comment]
This is the close button i am talking about.
![image](https://github.com/Naezr/ShyFox/assets/60490474/f562fdd2-6375-4737-84ca-5a38d4ebb148)

By the tree like structure i mean the parent and child like relation in the tabs.
![image](https://github.com/Naezr/ShyFox/assets/60490474/115820fc-4d18-48cf-be74-f39e48b06f45)
Sorry for low quality image it is an screenshot from my older config.

**Comment by Naezr** [comment]
I have a tree structure of tabs working, don't know why you don't. Try resetting Sidebery to factory settings and then re-import the style. 
![изображение](https://github.com/Naezr/ShyFox/assets/95460152/7914fa58-a451-4e07-82f5-a25e53e16dab)

About the close button, do you want to remove it completely in all panel states? Or do you want to make it transparent the moment it shrinks to the edge of the window?

**Comment by Naezr** [comment]
I don't know what kind of system you have, but on my GNOME system in this state this button looks like this
![изображение](https://github.com/Naezr/ShyFox/assets/95460152/fd82ad1d-b3f9-42ad-8668-9a5f7c5b382c) ![изображение](https://github.com/Naezr/ShyFox/assets/95460152/2e9da6dc-0996-47a1-ba25-24d9af29530e)

**Comment by niksingh710** [comment]
Tree tabs somehow got disabled in sideberry.
and yeah i use custom desktop setup.
i just want to hide the button completely as i use keybind to manage window.

**Comment by niksingh710** [comment]
![image](https://github.com/Naezr/ShyFox/assets/60490474/885e2cd6-d803-4e14-8e99-15cdc1371011)
@Naezr I am not getting these floating bookmarks or bookmarks folders ig.
I am not even actually sure what they are, but they look nice.
I guess you should also create a discussion tab in github.

**Comment by Naezr** [comment]
To enable the Bookmarks toolbar you can right click on an empty space in the navbar and toggle the Bookmarks toolbar to always show. 

![image](https://github.com/Naezr/ShyFox/assets/95460152/312f7405-9d2e-4971-9da5-7b82f4d6012e)

To make a folder in the bookmarks bar you can right-click on an empty space in the navbar and click the corresponding item. To add icons to folders, just type an emoji in its name. 

![image](https://github.com/Naezr/ShyFox/assets/95460152/11aaa174-8696-441e-8169-b444152253c1)

To add icons to folders, just type an emoji in its name. 
![image](https://github.com/Naezr/ShyFox/assets/95460152/9e46e170-deb8-43b2-9d20-02e367808b09)

About the discussion tab. I didn't even know that existed, but it sounds cool, I'll enable it
