### ISSUE TITLE
Youtube full screen behavior

### ISSUE THREAD

**Issue by engkel** [Naezr/ShyFox#28]
When using youtube, I encountered strange behavior when clicking on the 'full screen' button on youtube.com
![L5lpwlkMYa](https://github.com/Naezr/ShyFox/assets/47790315/899d3657-203b-4153-824d-a653b9855e56)

Instead of taking up the whole screen as expected, only some of the interface is hidden and the video remains quite small. Below the video, you can still see comments and recommended videos as well (not shown in this screenshot): 
![firefox_kI5RaltXou](https://github.com/Naezr/ShyFox/assets/47790315/08e45c64-1642-43e6-8d4f-ea803113989d)

For comparison, the full screen video feature as it looks in Chrome (Just for comparison): 
![chrome_DDeyoNsP7N](https://github.com/Naezr/ShyFox/assets/47790315/6e0761fc-0a9f-40fd-9937-814060bea868)

Let me know if this behavior is a result of user error or if I need to provide further info that could be helpful.

shyfox 3.0
Firefox 124.0.1
Windows 10

Ed.: This full screen behavior is the same on other pages like disney+ or hbomax - not exclusive to youtube.

**Comment by Naezr** [comment]
I have everything working on linux, I'm going to go see what happened to firefox for windows

**Comment by Naezr** [comment]
I installed a clean windows 10 22H2 on a virtual machine, installed firefox 124.0.2 there and installed ShyFox on it. Fullscreen videos work fine here. I don't know what this error could be related to, try reproducing this on a clean profile

**Comment by Naezr** [comment]
I made a small correction, now fullscreen videos should definitely work fine, if it doesn't, please report it

**Comment by Naezr** [comment]
I didn't see the report, so I'm closing it
