### ISSUE TITLE
About the pin tab

### ISSUE THREAD

**Issue by sty-sun** [Naezr/ShyFox#29]
I am trying to pin a new tab for one specific workshop, but it seems that the pin tab is pinned for all the workshops, so I'm wondering how I can pin one tab for one workshop?

**Comment by Naezr** [comment]
Ask the Sidebery developers about this, it's not something I can help with. https://github.com/mbnuqw/sidebery

**Comment by sty-sun** [comment]
> Ask the Sidebery developers about this, it's not something I can help with. https://github.com/mbnuqw/sidebery

Thanks for ur reply, I have solved this problem. Actually, it's a setting about the pinned tab in sidebery. The only thing that I have to do is turn the station of the pinned tab position from ‘Globally top’ to ‘in pannel-top’
