### ISSUE TITLE
Utils

### ISSUE THREAD

**Issue by kittenvr** [Naezr/ShyFox#3]
You listed the chrome hyarchy and said there is a utils folder but I don't see it, where can I download it?

**Comment by Naezr** [comment]
The installation instructions say to install fx-autoconfig. Install it and you will understand

**Comment by Naezr** [comment]
I don't understand what the problem is, what you want.

**Comment by kittenvr** [comment]
i didnt follow the guide fully

**Comment by Naezr** [comment]
I think the issue was resolved, or there was no issue at all. If not, just reopen it.
