### ISSUE TITLE
Firefox update

### ISSUE THREAD

**Issue by Dotdk** [Naezr/ShyFox#30]
seems the update from firefox destroyed the theme is it right or me there does somthing wrong?

**Comment by Naezr** [comment]
I have everything working fine in flatpak version of firefox 124.0.2 for linux. Maybe something is broken for windows, I'll go check it out

**Comment by Dotdk** [comment]
when i put the crome files in nothing changing just reformated my machine so had to reinstall

**Comment by Naezr** [comment]
Are you sure you put the `chrome` folder in the right place? And you didn't forget about `user.js`? You can try to manually go to `about:config` page and set `toolkit.legacyUserProfileCustomizations.stylesheets` to `true`
