### ISSUE TITLE
Spaces for bookmarks didn't remove completely when bookmarks and sidebar are hidden.

### ISSUE THREAD

**Issue by Banboo-on-Github** [Naezr/ShyFox#33]
![image](https://github.com/Naezr/ShyFox/assets/27681401/1b8cfc99-0ab0-4c4d-add9-1fbc48e981a2)
Also the sidebar will be extremely laggy if bookmarks are too many.

**Comment by Naezr** [comment]
Somehow [there](https://github.com/Naezr/ShyFox/commit/2d9ab09b664ab809a2f466e503e1469294a49a49) was an extra bracket that broke everything, now the bookmarks bar hides as it should.

About the lags, tell me more about that. What do you have to do to make it lag? What does it lag and how?

**Comment by Banboo-on-Github** [comment]
Thanks for your fix!

I have about 750 bookmarks. The hidden sidebar works fine untill I opened a folder.
![temp](https://github.com/Naezr/ShyFox/assets/27681401/22553bcf-e828-4ded-8235-320c1bfe3174)
The cpu usage went up a lot. Maybe this problem is from firefox or my pc I think.
