### ISSUE TITLE
Firefox 125 broke the window control buttons

### ISSUE THREAD

**Issue by Naezr** [Naezr/ShyFox#35]
I'm aware of this and I'm working on a solution

**Comment by Naezr** [comment]
As far as I understand it, they only broke the buttons on linux. On Windows 10 and Firefox 125 everything remains as before. I don't have a Mac, so I don't know how things are there.

**Comment by ZhymabekRoman** [comment]
Thanks for the project!
Got same problem, fixed by adding `.titlebar-buttonbox-container {display:none !important;} ` into `userChrome.css`.

Firefox developer edition. Version: 126

**Comment by Naezr** [comment]
@ZhymabekRoman 

Be aware that the theme only supports the latest version of Firefox. I am not responsible for how it behaves on previous versions of the browser. I update the theme to fit new realities and these updates may not be appropriate on previous versions of Firefox. At the moment the latest version is 127. 127.0.2 to be exact. I do not provide support for earlier versions, including 126.

**Comment by ZhymabekRoman** [comment]
Ahhh, okay. Thanks you @Naezr!
