### ISSUE TITLE
The shortcut for `Userchrome Toggle` extension failed to re visible bars.

### ISSUE THREAD

**Issue by H1DDENADM1N** [Naezr/ShyFox#36]
I just updated to `Firefox 126.0b5` with `Windows 11 24H2 26100.1`.

The shortcut for `Userchrome Toggle` extension (`Ctrl Shift 1`, `Ctrl Shift 2`, `Ctrl Shift 3`) failed to function.

I noticed the checkbox buttons can visible or hide bars, and the shortcut key can hide it but can't revisable it.

![图片](https://github.com/Naezr/ShyFox/assets/65646535/7a9cac08-2f21-49ae-99cc-9da19b20d991)

I have tried to change the shortcuts to other keys, but it's still not working.

**Comment by Naezr** [comment]
It's working fine for me. Try creating a new clean Firefox profile and check there. My Browser Toolbox broke after one of the updates, for example. I had to delete the toolbox cache from my profile to fix it. Maybe you had something similar happen to you, but with an extension? Let's not guess, just test it on a clean profile and if it's the same issue, then I'll take care of it.

**Comment by Naezr** [comment]
I confirm there is a problem, I have no idea what to do. Most likely something was changed in firefox 126 that affected UserChrome Toggle. This extension hasn't been updated for a long time and it looks like it's starting to die. 

I actually only studied CSS for the purpose of creating themes for firefox, it's basically my first project. Looks like it's time to take on JS and rework UserChrome Toggle

**Comment by H1DDENADM1N** [comment]
>Looks like it's time to take on JS and rework UserChrome Toggle

Cool,  expecting you to make the toggle shortcuts workable again.
