### ISSUE TITLE
sidebery visual issues

### ISSUE THREAD

**Issue by xx90three** [Naezr/ShyFox#37]
Hi there, thanks for making this, I adore this theme.
I ran into a bit of a problem with sidebery. I followed the instruction and removed my old style for sidebery but for some reason there are pointy ends in the corners of the sidebar. Is there a way to remove them? 

firefox 125.0.2

![Screenshot 2024-04-28 022037](https://github.com/Naezr/ShyFox/assets/131922557/2342db30-46ee-4c2b-a3e6-965846b974dc)
![Screenshot 2024-04-28 022038](https://github.com/Naezr/ShyFox/assets/131922557/b70dca48-6aca-4a86-ba45-300e4619ef26)
![Screenshot 2024-04-28 022039](https://github.com/Naezr/ShyFox/assets/131922557/0d3452ad-c405-4bd2-80b3-5d2bf8df7690)

**Comment by Naezr** [comment]
Try reducing the `--big-rounding` a bit in the `shy-variables.css` file. 


There is no such problem on Linux, so I didn't pay attention to it. I have ideas on how to fix it, but I don't have time to work on this theme right now. When Mozilla breaks something again or I just want to update this theme somehow, I will pay more attention to testing on Windows.

**Comment by xx90three** [comment]
reducing --big-rounding fixed it. Thank you!
