### ISSUE TITLE
Can "Shy mode" only be enabled when Firefox is maximized?

### ISSUE THREAD

**Issue by themegaxandy** [Naezr/ShyFox#39]
Firstly I would like to thank you for this incredible customization. I loved the idea and thought it was very well done.

That's why I'd like to help improve it. Currently, it is a little complicated to access the side menus when Firefox is in windowed mode. As you can see below.
![Windowed](https://github.com/Naezr/ShyFox/assets/7902295/ad17e405-d946-45a6-9f5a-5d45f7a2caf5)

For comparison purposes, below is how it works in maximized mode. Accessing the side menus is very easy and quick.
![Maximized](https://github.com/Naezr/ShyFox/assets/7902295/16a8c6c7-a346-4593-bf46-fa8ffd4a5563)

Would there be any way to facilitate access to the side menus while Firefox is in windowed mode? Maybe make Firefox only stay in "Shy mode" while it's maximized?

(I'm using this customization on Windows 11)

**Comment by Naezr** [comment]
That's a good idea. I should actually work on the window mode. I mostly use the browser in maximized state and am focused on that.

It would be interesting to hear your ideas. For example I could make the window border thicker in windowed mode to make it easier to point. But that would look weird. I could also bring back the panels sticking out of the window border, as they did in early versions of ShyFox. All in all, it's more a matter of idea and concept than practical implementation

**Comment by themegaxandy** [comment]
I don't know if it would be possible, but maybe you could increase the "hitbox" of the edges, but without actually increasing the edges. Thus, the edges would be larger virtually, but not visually. This would somewhat prevent the user from clicking on the edges of the site, yes, but I don't think there are any sites that require the user to click on the extreme edges. Maybe it would be a good solution.

**Comment by Naezr** [comment]
I've added hitboxes to the panels in windowed mode. You can resize them [here](https://github.com/Naezr/ShyFox/blob/main/chrome%2FShyFox%2Fshy-variables.css#L42)

**Comment by themegaxandy** [comment]
Perfect, adding a larger hitbox in windowed mode, and still being able to customize this value, helped a lot!
