### ISSUE TITLE
Firefox laggy with ShyFox

### ISSUE THREAD

**Issue by BLACK4585** [Naezr/ShyFox#42]
Hey, I just updated from the old version, where fx-autoconfig was still required.
My Firefox is now pretty laggy, like sometimes it has little freezes or things take ages to load.

Could this be related to ShyFox in any way and can I debug that somehow?
I can't remember myself installing anything else that could slow down the browser.

**Comment by Naezr** [comment]
The fx-autoconfig is a very strange and unpredictable thing, maybe you deleted it wrong somehow or something. Try creating a new clean Firefox profile, or as a last resort reinstall the whole browser. 

What's your OS, Firefox version, computer specs?

**Comment by BLACK4585** [comment]
I think I just followed your guide from the readme, will check it all again though.
I'm on Firefox 126.0.1 with Win11. I'm using an Intel Core 19-12900K and a RTX 3070ti with 32 GB Ram, so that shouldn't be the case.
Furthermore, I will try to use a new profile. Apart from the chrome folder and the files in the Firefox install dir, there are no other files belonging to fx-autoconfig?

**Comment by Naezr** [comment]
My computer is many times weaker than yours and I have everything running smoothly. Maybe there is some cache left in the browser profile or something, I don't know. I gave up on fx-autoconfig a long time ago, but as far as I know it doesn't create any files other than the ones you put in yourself

**Comment by Naezr** [comment]
The cache associated with fx-autoconfig may remain in the `startupCache` folder in your profile. This cache stores, among other things, fx-autoconfig scripts to speed up startup. It is possible that these cached scripts are trying to access non-existent or inaccessible functions and this is causing lags. Or maybe I am talking nonsense. But if you don't get lags on a clean profile, try to go back to the old one and remove the `startupCache` folder from it.

**Comment by Naezr** [comment]
I guess you've solved your problem since you don't reply here anymore. I declare the issue closed. If not, open a new issue or ask directly in this one
