### ISSUE TITLE
Pannels stuck

### ISSUE THREAD

**Issue by JoyHak** [Naezr/ShyFox#47]
_Немного контекста: я переехал с win10 v1809 LTSC на win10 v22H2 Pro и обновил LibreWolf v125 на v127._ 

_Я заметил много неприятных изменений например пропала возможность автоматически открывать новую вкладку если ты закрыл последнюю. Однако к ShyFox относится другая проблема._

Когда я нажимаю кнопку расширения на панели и теряется фокус, окно расширения сворачивается, а кнопка расширения на панели остается активной, словно она нажата. При этом панель не исчезает и зависает. Это касается любых кнопок включая встроенные, например профиль пользователя Firefox или история браузера также может зависнуть на панели при открытии элемента истории.

После перезапуска браузера эффект пропадает. Иные действия не исправлют ситуацию. 

                                                        ───── ⋆⋅☆⋅⋆ ─────

When I press the extension button on the toolbar and lose focus, the extension window collapses, but the extension button on the toolbar remains active as if it were pressed. The toolbar does not disappear and stucks. This issue affects **any buttons**, including built-in ones, such as the Firefox user profile or browsing history. 

After restarting the browser, the effect disappears. No other actions resolve the situation.

https://github.com/Naezr/ShyFox/assets/156242738/be5e89d5-f411-48af-8726-e2fad694c3ac

**Comment by JoyHak** [comment]
Кнопка профиля зависает при нажатии до открытия страницы; при нажатии ср. кнопкой мыши.

https://github.com/Naezr/ShyFox/assets/156242738/54326b0f-16c2-4b52-bd2a-bb57bee74a32

**Comment by Naezr** [comment]
Ничего знаю на счёт LibreWolf и изменений, которые он вносит относительно обычного Firefox, я им не пользуюсь. А о проблеме этой я знаю и пытался её решить, но пока, как видно безуспешно. 

Суть бага в том, что попапы от расширений по какой-то причине являются дочерними элементами `#nav-bar` - панели, где находится адресная строка. И если этот самый навбар пошевелить в момент, когда попап расширения открыт, то этот попап сжмыхнет и произойдёт то, что видно на видео. Все остальные попапы являются дочерними элементами `#mainPopupSet` и всё работает нормально. 

Я не представляю, на какие ухищрения надо пойти, чтобы пофиксить это на стороне CSS темы, тут надо чинить код самого Firefox. Но разработчики это и за баг не посчитают скорее всего, ибо у них всё работает, это я со своими CSS стилями всё поломал. 

Из того, что я выяснил, то браузер можно не перезапускать, достаточно выключить и включить в настройках расширение, кнопка которого залипла. 

И по поводу неприятных изменений, упомянутых в начале, можно поподробнее?

**Comment by JoyHak** [comment]
Изменения в основном касаются самого фокса. Дело в том, что librewolf является надстройкой над движком фокса и по настройкам / визуалу почти не отличается. Именно поэтому для меня это почти firefox.

Собственно после переезда **пропало автооткрытие новой вкладки при закрытии последней**. Казалось бы, в firefox такого никогда не было _(по заверениям интернета)_, однако я пользовался этой функцией очень долго, а сейчас её нигде нет: ни в настройках sideberry, ни в настройках браузера. Проверил все версии со 124-й и ничего не нашел... 

Флаг `browser.tabs.closeWindowWithLastTab` из `about:config` не работает: sideberry перестает видеть новые вкладки и будто умирает.

**Comment by Naezr** [comment]
> Собственно после переезда **пропало автооткрытие новой вкладки при закрытии последней**. Казалось бы, в firefox такого никогда не было _(по заверениям интернета)_, однако я пользовался этой функцией очень долго, а сейчас её нигде нет: ни в настройках sideberry, ни в настройках браузера. Проверил все версии со 124-й и ничего не нашел...

Я обычно держу много открытых вкладок, многие выгруженными из памяти, плюс всегда есть несколько закреплённых, так что надобности в таком функционале у меня нет.

> Флаг `browser.tabs.closeWindowWithLastTab` из `about:config` не работает: sideberry перестает видеть новые вкладки и будто умирает.

Проверил, всё также и в обычном фаерфоксе

**Comment by Naezr** [comment]
Нашёл настройку в Sideberry, это надо для каждого пространства отдельно включать.
Пкм по пустому месту в сайдбаре > настройки панели

![image](https://github.com/Naezr/ShyFox/assets/95460152/7db0c365-485d-4d1c-925c-d9a94dc2e3f0)

**Comment by JoyHak** [comment]
А я как раз убрал эту настройку из контекстного меню)))))))))
Спасибо!
