### ISSUE TITLE
Right click menu is fully transparent

### ISSUE THREAD

**Issue by jae1911** [Naezr/ShyFox#49]
Testing ShyFox, it seems the right click menu is fully transparent:

![firefox_ngQnooNaRe](https://github.com/Naezr/ShyFox/assets/76598503/998d17c0-110d-4371-97b7-2d944aa2e705)

Is there something I missed in the installation instructions?

Using Firefox 127.0.1 on Windows 11 using the ShyFox version that has this commit as latest: https://github.com/Naezr/ShyFox/commit/bf7703b5b74d4ebf90f5a3846bea7be1f35826c8.

**Comment by Naezr** [comment]
Sorry, but right now I don't have the ability to investigate this issue as I don't have access to my computer. As a temporary solution you can comment out this section:

https://github.com/Naezr/ShyFox/blob/main/chrome%2FShyFox%2Fshy-global.css#L263-L279

I will come back to it later

**Comment by Naezr** [comment]
Are you using `System Theme - auto`? Try just dark or light
#51

**Comment by jae1911** [comment]
> Are you using System Theme - auto? Try just dark or light

Yup, that was it, switching to dark theme solves the issue.
