### ISSUE TITLE
Fullscreen is not fullscreen

### ISSUE THREAD

**Issue by bihius** [Naezr/ShyFox#50]
The bottom has a few pixels margin like the right side. There is also a gap in top panel. 
![image](https://github.com/Naezr/ShyFox/assets/119067436/79a0a54d-152a-4854-b0d9-edbb08163401)

**Comment by Naezr** [comment]
Firefox version?

**Comment by Naezr** [comment]
Judging by the old version of GNOME, your Firefox isn't fresh either. The README has a badge with the version of Firefox that I have installed and on which everything works. As browser updates, I update the theme as well. Previous versions are not supported

**Comment by Naezr** [comment]
Has your issue been solved? No? If you're not answering, I have no intention of solving it.

**Comment by bihius** [comment]
Hi!
Sorry for late answer. The problem was related to custom gnome theme and probably to previous firefox modifications.
