### ISSUE TITLE
Background for some menus is transparent

### ISSUE THREAD

**Issue by Windowsxd** [Naezr/ShyFox#51]
Haven't seen anybody else comment about this, but I found some menus to have no background. pictures shown below:
![image](https://github.com/Naezr/ShyFox/assets/31010173/a42d28a2-93db-4bb8-a4d6-9630198484bb)

To explain the picture: the find panel at the bottom has a transparent background, the toolbar to the right has a transparent background (also I cannot put stuff in the toolbar, hence why there is only two items)
But the right click menu does have a background.

Running KDE plasma 6.1 on wayland using NixOS

**Comment by Windowsxd** [comment]
I have found the issue. Inside of shy-variables.css:
![image](https://github.com/Naezr/ShyFox/assets/31010173/54818493-1e0f-44d3-afda-fe793b6361e4)
tb-col is transparent. Me setting the value to rgba(0,255,0,0.5); made an ugly green that I can see. This means that toolbar-bgcolor is also transparent.

![image](https://github.com/Naezr/ShyFox/assets/31010173/93578476-6346-4acb-8099-d550fc2c3fbc)

**Comment by Naezr** [comment]
If you look at the changelog, one of the most recent changes was a redesign of the README. I decided to make it more tidy before posting it to r/unixporn. 

Before that, the Adaptive Tab Bar Color extension was a must-have. If you look in the recommended Adaptive Tab Bar Color settings below in the README, I mentioned there that the panels can be transparent for some reasons.

All these problems with transparent panels come from the lack of Adaptive Tab Bar Color. It's my mistake that I should have not tested the theme without it. As a temporary solution install it. And I'll have to work on making the theme work without it.

**Comment by Naezr** [comment]
It was a hasty explanation. There are other possibilities. Are you using `System Theme - auto`?

**Comment by Naezr** [comment]
Auto theme looks broken for me too
![image](https://github.com/Naezr/ShyFox/assets/95460152/63fec20c-ed47-4fd2-8c83-667cd801db25)
But just dark or light working fine
![image](https://github.com/Naezr/ShyFox/assets/95460152/0b826a93-e556-4486-904f-ba311b73781a)

**Comment by Windowsxd** [comment]
It seems like I was using system theme, and it fixed another issue but not the menu issue. 
Making the toolbar background color different from the tab bar background color in adaptive tab bar color plugin did fix it. Thank you

**Comment by Naezr** [comment]
I'll leave this issue open, as I need to figure out why your panels are transparent without Adaptive Tab Bar Color. I want to leave the possibility of choice in terms of colors.

**Comment by Windowsxd** [comment]
I use Adaptive Tab Bar Color, sorry if that wasn't clear. However, I did not use it inside of private windows, and my menu was transparent. Turns out that system theme auto was the cause for that issue, and my menus being transparent were fixed with changing the adaptive tab bar color settings
