### ISSUE TITLE
Userchrome.css does not take effect

### ISSUE THREAD

**Issue by FuryFiber** [Naezr/ShyFox#55]
After following the installation instructions it seems like something is wrong. After doing step 4 and restarting firefox there is no change.
Do you have any idea why this might be?

- i fully killed firefox
- `toolkit.legacyUserProfileCustomizations.stylesheets` is enabled in about:config
- chrome and user.js are copied into ~/.mozilla/firefox

**Comment by rybomir** [comment]
@FuryFiber 
Did you copy to your profile's folder? Ie. ~/.mozliia/firefox/_your-profile_/ ?

**Comment by Naezr** [comment]
Profile folder is `~/.mozilla/firefox/{random characters}.default-release`. There should be all sorts of folders and files, like `prefs.js`, `extensions` with `.xpi` files inside, `startupCache`, and lots of other stuff. The `chrome` folder and the `user.js` file should be placed with all of these.

**Comment by asyncedd** [comment]
Go to `about:profiles`. Find the profile which says "This is the profile in use and it cannot be deleted." and go to the `Root Directory`. After that, just drag the `chrome/` and the `user.js` in that directory.

**Comment by Naezr** [comment]
If there have been no questions for so long, the issue is probably resolved
