### ISSUE TITLE
Не закрывается боковая панель, после ее закрытия

### ISSUE THREAD

**Issue by Roman4iks** [Naezr/ShyFox#59]
![изображение](https://github.com/Naezr/ShyFox/assets/48359688/4ca94c78-7597-43a0-b283-53990ef4f5ba)

После нажатия на клавишу F1 панель закрывается, но пустое место остается с надписью Open Sidebery! Все делал по инструкции. Не до конца понял как добавить в стили в Sidebery 
![изображение](https://github.com/Naezr/ShyFox/assets/48359688/4651c7f2-a661-441a-bf13-1466535b468b)
Поэтому я просто вставил в поле где написаны стили, стили с файла.

Также при изменении стилей боковой панели инструментов на 3, разшерение показывает что, оно все равно открыто, хотя проблема остается той же (Пустое пространство в боковой панели)

**Comment by Naezr** [comment]
Вообще ничего не понял, давай с чувством, с толком, с расстановкой и по порядку. Что ты и как нажимаешь, куда что пропадает, что происходит вообще

**Comment by Roman4iks** [comment]
Захожу в браузер, открываю боковую панель, после пытаюсь ее закрыть, контент пропадает, а сам блок остается открытым
Открытая панель
![изображение](https://github.com/Naezr/ShyFox/assets/48359688/b351b0be-4b50-4b93-a298-c2b4b94f7718)

Закрытая панель
![изображение](https://github.com/Naezr/ShyFox/assets/48359688/ac8c8502-8dd4-4ea7-92f6-ac9c1cfc9f3c)

**Comment by Naezr** [comment]
Каким образом закрытие панели происходит, что ты нажимаешь?

**Comment by Roman4iks** [comment]
Независимо от кнопки закрытия она не пропадает (И на кнопку разшерения нажимал и на F1)

**Comment by Naezr** [comment]
Не надо никакие кнопки закрытия нажимать, сайдбар всегда должен быть открыт во внутренней логике браузера. Чтобы скрыть сайдбар нажми Toggle style 1 в окошке том, или сочетание клавиш, которое сам назначил. Если не назначил, то по умолчанию это `ctrl` + `shift` + `1`

**Comment by Roman4iks** [comment]
Понял, принял, все заработало. Спасибо огромное!

**Comment by Naezr** [comment]
А toggle style 3 не нажимай, это только с клавиатуры, в интерфейсе кнопка залипает. Я об этом знаю, но починить не знаю как
