### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by dm090504** [Naezr/ShyFox#6]
it doesnt look like the gif 

![afbeelding](https://github.com/Naezr/ShyFox/assets/156821989/25905471-41a2-4264-9af0-cf93218ba6e7)

**Comment by Naezr** [comment]
Go to about: config and set `toolkit.legacyUserProfileCustomizations.stylesheets` to `true`. Also this theme don't work on ESR.

**Comment by dm090504** [comment]
thanks
