### ISSUE TITLE
urlbar disappears into mac menubar on sonoma 14.5, probably specific to ver 3.5 because it didn't happen before i updated

### ISSUE THREAD

**Issue by jaashuu** [Naezr/ShyFox#62]
https://github.com/Naezr/ShyFox/assets/74874572/cb25ba19-ef4b-4575-bed7-2777eb4d8dd9

updated to 3.5, and now when i search it does this. it's not a huge problem since i do have the 3.4 files somewhere on my computer, but figured i'd open an issue for it.

**Comment by Naezr** [comment]
In fact, the changes to the search bar were minimal in this update. Try rolling back only the `shy-floating-search.css` file

**Comment by Naezr** [comment]
As I understand it, the theme otherwise works fine on macOS? I'm glad to know that

**Comment by jaashuu** [comment]
i don't think it's an issue with the floating search file. before i rolled back to 3.4 files i had import shy-floating-search.css commented out in userchrome.css, and even then, it did something similar even with the popup search.

**Comment by Naezr** [comment]
There was a person here who had the search bar break down in a similar way. He reinstalled the theme on a clean profile and everything was fixed.

Very, very often the cause of the error is your messed up profile folder.

**Comment by Naezr** [comment]
@jaashuu is this issue still here?

**Comment by jaashuu** [comment]
i didn't completely reinstall, since that's a huge hassle i don't have time for at the moment. however, it seems to be something with the shy-sidebar.css file. i decided to go and try each file one by one with the old 3.4 version compared to the 3.5+ versions and shy-sidebar.css was the one chat caused the urlbar according to what i found

**Comment by Naezr** [comment]
https://github.com/Naezr/ShyFox/commit/b0f676ff77d376633c5984860fc6cc0c48b5e683#diff-65ba196e048edfca7814c48020b5bce5aea31953a537c6ff8cf072c733aa4aa9

The changes to the `shy-sidebar.css` file between 3.4 and 3.5 are minimal and do not obviously affect urlbar. So I don't know what to do about it

**Comment by jaashuu** [comment]
i'm going to close this because it seems like it has been resolved once i updated to 3.8+.
