### ISSUE TITLE
When hiding Address Bar, sideberry appears automatically

### ISSUE THREAD

**Issue by Momen-MKadry** [Naezr/ShyFox#65]
Hello, I have a problem, now I'm hiding sideberry, I want to hide the address bar too, so I press the shortcut and it collapses but sideberry emerges after that, also the sidebar and sideberry can't be hidden together, if I hide one the other emerges if it was hidden

**Comment by Naezr** [comment]
Do you applied "Allow multiple styles to be active together" Userchrome Toggle  setting?

**Comment by Momen-MKadry** [comment]
It wasn't on but I turned t on now and the issue is still here

**Comment by Naezr** [comment]
Click "Apply Settings"

**Comment by Momen-MKadry** [comment]
Oh, I forgot to do that 💀, it's fixed now thanks a lot
