### ISSUE TITLE
Collecting feedback

### ISSUE THREAD

**Issue by Naezr** [Naezr/ShyFox#7]
Do you like the fact that the controls are divided into three separate panels? Do you like the fact that they only show up when you hover? Let's say I could make the right panel always visible and hide it only together with the left tab bar. I was inspired by a long comment under a post on reddit and decided to ask users. Leave your feedback, impressions and ideas here

**Comment by DADA30000** [comment]
This theme is just ideal for me, it is exactly what I was looking for!
Also it would be nice to have some key shortcut to hide all panels completely

**Comment by Naezr** [comment]
Actually Userchrome Toggle provides very limited features, but I have plans to implement independent panel switching using fx-autoconfig. Right now JavaScript is used minimally because I don't know how to use it. But I want to learn and make something really interesting.

**Comment by Naezr** [comment]
https://github.com/Naezr/ShyFox/assets/95460152/8f92dc12-0c49-47aa-bc3b-f61389830a16

**Comment by Naezr** [comment]
It's harder than I thought

https://github.com/Naezr/ShyFox/assets/95460152/1a131031-8867-41d9-ba7c-c76a4fbaeb6d

**Comment by ex1side** [comment]
At first it seemed that it would be inconvenient to constantly hover the mouse to make the panel appear, but this theme is just great to use, you get the maximum useful space for content, because the panels do not take up space

**Comment by Naezr** [comment]
Some cool early-dev features
https://github.com/Naezr/ShyFox/assets/95460152/31bc61ae-40f5-429a-93f4-d422de7d33c5

**Comment by leakspin** [comment]
For me, having three panels is perfect, but I would like to have a configuration for having panels hidden by default. I don't usually use the right side panel and fills that bit of space that makes some websites to change from desktop to mobile view, so I need to hide it.
But I have the browser in three different screens, so I would have to configure UserChrome toggles every time I launch the browser in every window (and in every new window that I open).

So what I propose is to have some sort of setting for having panels hidden by default.

Also, thanks a lot for this theme! I really love it!
