### ISSUE TITLE
unable to print, ui blocking the print & cancel button

### ISSUE THREAD

**Issue by jaashuu** [Naezr/ShyFox#70]
![Screenshot 2024-06-28 at 14 07 10](https://github.com/Naezr/ShyFox/assets/74874572/d2a0f0bb-b98d-462d-a86a-836eeb7387ba)
there is the large slightly transparent dark thing that extends from the middle buttons and all the way to the edge of the screen, and it expands when you zoom out. it makes the print & cancel button unclickable.

**Comment by Naezr** [comment]
I didn't even realize it was possible to print in Firefox

**Comment by Naezr** [comment]
Forgot to mention it here, but the solution has already been pushed on nightly branch. When there are enough changes there and I've tested them, it will go to main.

https://github.com/Naezr/ShyFox/commit/2f91d5d2a042640d7037683a4d8a461ffa4eaa9c
