### ISSUE TITLE
Dragging open tabs on end is acting weird

### ISSUE THREAD

**Issue by vavakado** [Naezr/ShyFox#72]
Этой проблемы не возникает наверху панели

https://github.com/Naezr/ShyFox/assets/80159210/2be04c61-3cc5-4392-8593-2af4e6b00f39

**Comment by Naezr** [comment]
Если что, я знаю об этой ошибке, но вообще понятия не имею, как это починить. У меня эти штуки ведут себя примерно также

------

I'm aware of this bug, but have no idea how to fix it at all. I have these things behaving in much the same way

**Comment by Naezr** [comment]
По идее пофикшено в https://github.com/Naezr/ShyFox/commit/fba6d3616a83441370a42102ba3b36ee80fbac8c
Обсуждение перемещается в issue выше, где человек подсказал, как это починить
