### ISSUE TITLE
Laggy Search Bar experience

### ISSUE THREAD

**Issue by daedalus-ode** [Naezr/ShyFox#74]
**1st up. Amazing work. Respect and thanks to all who made this.**
A tiny issue popped up when trying to search something while the search bar is hidden. When trying to type something into the focused address bar, you can feel a significant lag. 
Similar experience occurs for the floating toolbar also. Hiding/floating an element causes it to become less snappy.
I'm working on a mid tier laptop. Is that really an issue?

### Replicating the issue:
1. Hide Search/Address bar 
2. Press Ctrl+L 
3. Type anything quickly

**Comment by synqqrawr** [comment]
I'm on a Intel Core i7-6500U. It's not too bad for me. Though, I find it practically unusable with IMEs (I'm talking about FCITX here). 

@Naezr you could make an option to disable it via:  
```css
@import url("search-bar-tweak-blah-blah.css") (-moz-bool-pref: "uc.tweak.XXX");
```

Although I find that weird

**Comment by Naezr** [comment]
> Respect and thanks to all who made this.

If you're interested, I created this theme and am working on it alone.

On my old laptop (dual core i7-7500u, 12gb ram, gtx 950m) I also experienced some lags with a game open in the background or something else heavy. Also Browser Toolbox can cause some pretty noticeable lags. 

My new laptop is doing better, but again the causes of lags are the same. In vanilla Firefox there are practically no animations, so lags are not felt there. However, Firefox's html/css code is quite convoluted and the added confusion of having such a complex theme written on top of it affects performance.

**Comment by Naezr** [comment]
> you could make an option to disable it via:

An ShyFox update has been released, so

`shyfox.disable.floating.search` > `true` 

This setting disables the floating search bar. If it gets rid of the lags, be happy. Otherwise, don't be happy, because the lags is for another reason.

**Comment by synqqrawr** [comment]
> > you could make an option to disable it via:
> 
> An ShyFox update has been released, so
> 
> `shyfox.disable.floating.search` > `true`
> 
> This setting disables the floating search bar. If it gets rid of the lags, be happy. Otherwise, don't be happy, because the lags is for another reason.

![image](https://github.com/user-attachments/assets/e13c2781-fb9f-4aaa-9815-dee7ef86480a)

It looks like this now. :P

**Comment by Naezr** [comment]
![изображение](https://github.com/user-attachments/assets/165660e5-8fbd-4257-94cc-b39266f45408)
Your system, browser version? Did you use any other modifications before installing ShyFox? Does the same problem appear on a clean profile?

**Comment by synqqrawr** [comment]
![image](https://github.com/user-attachments/assets/a13c5e98-12b6-4638-beaa-09426b518b55)

Ya, seems like a me issue for me :P. sorry.

**Comment by Naezr** [comment]
> also ignore that terrible default theme, i don't know what happened

![image](https://github.com/user-attachments/assets/0e2de44b-d8da-496a-95db-e6b17ae5bc21)
