### ISSUE TITLE
macOS issues

### ISSUE THREAD

**Issue by LiquidLemon** [Naezr/ShyFox#76]
Hey, I just wanted to start by saying great work. This theme looks amazing and I didn't even know something like this was possible in Firefox (we definitely need more themes like this). I tried running this theme on macOS and I found a few issues. I don't know if you're at all interested in including compatibility but I would be grateful if you have any pointers how to approach fixing the issues I found.

# Address bar
It's kind of hard to explain but when I click the address bar the cursor is stuck in highlight mode. When I move it (without pressing any mouse buttons) the address gets highlighted from the start of the URL. This doesn't happen on the first time I click it after launching the browser. Selecting the address via shortcut works as expected though. I can provide a video if you want.
<img width="488" alt="image" src="https://github.com/Naezr/ShyFox/assets/9415789/36bbd3f1-fca3-44b7-a487-7ed1ae65482f">

# Sidebery
Sidebery doesn't really work as expected :(

## Overlapping window controls
This is pretty much expected since it wasn't accounted for, though I'm a little surprised to see that the sidebar stretches all the way to the top of the window.
<img width="339" alt="image" src="https://github.com/Naezr/ShyFox/assets/9415789/f43ba58b-d1d6-461b-98ad-0089fd006528">

## Pinned tabs
The styling doesn't seem to work at all:
<img width="302" alt="image" src="https://github.com/Naezr/ShyFox/assets/9415789/be598bd7-68d0-4a50-b17a-240ed0a5c198">

## Touchpad/trackpad
I found out that switching tab panels with horizontal scroll is completely unusable on touchpad. I don't actually know if this is macOS exclusive. You can technically try to tune it (https://github.com/mbnuqw/sidebery/issues/1252) but I haven't been able to get it to work reliably. It's pretty confusing and I didn't even know that it's a feature so maybe you could mention it in the README to save others some confusion (unless this really is just a macOS issue).

--- 
Like I said I'd appreciate any help with fixing these issues. I don't have any experience in modifying browser styles but if you point me in a direction I'd be happy to try troubleshooting it on my own.

**Comment by LiquidLemon** [comment]
I noticed you had bookmarks next to the buttons in screenshot so I enabled the bookmarks toolbar (I never use bookmarks) and now it works (the margins are a bit ugly but I suppose nothing can be done about that). 
<img width="348" alt="image" src="https://github.com/Naezr/ShyFox/assets/9415789/bb2ccf2f-98b9-4bee-817e-847994bc098e">

**Comment by LiquidLemon** [comment]
I resolved the lack of styling in Sidebery - I was using a symlink and looks like Firefox is happy to load `userChrome.css` from a symlink but not `userContent.css`.

**Comment by Naezr** [comment]
> When I move it (without pressing any mouse buttons) the address gets highlighted from the start of the URL.

I get exactly the same behavior in situations where the urlbar goes to full screen mode and there is already some text in it

https://github.com/Naezr/ShyFox/issues/66

> This is pretty much expected since it wasn't accounted for, though I'm a little surprised to see that the sidebar stretches all the way to the top of the window.

Intended behavior. Use Sidebery settings to leave empty space for buttons.

![image](https://github.com/Naezr/ShyFox/assets/95460152/597c93aa-e1ef-4f94-8d16-78442614e567)
![image](https://github.com/Naezr/ShyFox/assets/95460152/a1ca06dc-bf49-4aad-8d14-203bd2db86ff)

> I was using a symlink

I use symlinks too. I use them to synchronize files with GitHub in semi-automatic mode. And they didn't work for me the first time. First you have to put the real files in and run Firefox once. After that you can replace the files with symlinks. 

> I don't know if you're at all interested in including compatibility

I am interested in this and am testing the theme on Windows, even though I use Linux myself. However, I don't have a Mac and can't test the theme there

> I don't have any experience in modifying browser styles but if you point me in a direction I'd be happy to try troubleshooting it on my own.

https://www.reddit.com/r/FirefoxCSS/wiki/index/tutorials/

**Comment by Naezr** [comment]
@LiquidLemon 

Right now in the nightly branch I'm testing and adding icons to the context menu. On Linux everything was fine initially, but for Windows I had to make some adjustments so that the text doesn't overlap the icons. I'd like to see how this behaves on macOS. If you don't mind, could you please test this for me?

**Comment by LiquidLemon** [comment]
@Naezr sure thing, do you have any reference for how it should look?

**Comment by Naezr** [comment]
@LiquidLemon 
Linux:
![изображение](https://github.com/Naezr/ShyFox/assets/95460152/a1de3a92-46c7-4ec9-8813-9e6aba73bf10)
Windows:
![изображение](https://github.com/Naezr/ShyFox/assets/95460152/c64406d6-1371-4bcd-ae39-2bc152bc3d26)

**Comment by LiquidLemon** [comment]
Here's how it looks:
![image](https://github.com/Naezr/ShyFox/assets/9415789/2ecf6e11-5c97-4877-ab85-1d10f7065e41)

Unfortunately, I had to toggle `widget.macos.native-context-menus` to get it to show up because by default on macOS Firefox uses native context menus. So without disabling that feature I get just a normal menu:
![image](https://github.com/Naezr/ShyFox/assets/9415789/c0ef8334-4a31-45ed-9b27-ca81abbb1a3e)
(I imagine the icons need to be passed in some other way and can't just be added in CSS for that)

**Comment by LiquidLemon** [comment]
Well TBH I think most people won't ever see this, I had to go and look up if there even was a way to disable the native menu.

**Comment by Naezr** [comment]
It is enough to add a mention in the readme. Anyway I intend to add settings via `about:config` to turn off context menu icons, floating urlbar, etc. Toggling one more value won't make things harder.

**Comment by Naezr** [comment]
@LiquidLemon 

I've updated the nightly branch.

Expected changes for macOS:
- The corners of the non-native context menu are not rounded, as it is wrapped in the native menu shell.
- Items `back`, `forward`, `reload` and `bookmark` should get icons
- Icons of extensions with the standard icon should stand exactly on the grid with the monochrome ones.

Note that context menu icons and monochrome extension icons should now be activated via `about:config` (check README). They are disabled by default

**Comment by LiquidLemon** [comment]
<img width="242" alt="image" src="https://github.com/Naezr/ShyFox/assets/9415789/5eccf7cd-564e-4ee7-93a3-e96906c2c56d">

The corners look better now but the icons completely vanished

**Comment by LiquidLemon** [comment]
<img width="248" alt="image" src="https://github.com/Naezr/ShyFox/assets/9415789/e8a8a900-166a-4ef7-b257-66b4f0bf0e34">

Looks great (sorry if you saw the previous comment, I need to learn to read before doing things 😅 )

**Comment by Naezr** [comment]
Re-read my previous message. Icons are now disabled by default. To turn them on you need to write a special value in about:config. These values are specified in the README of the nigtly branch.

**Comment by LiquidLemon** [comment]
@Naezr yeah, I'm sorry I thought I'd fix that before you had the chance to read it. I feel really silly about missing that.

**Comment by Naezr** [comment]
I feel like I'm too fast, as I read notifications almost immediately after they come in. Sometimes I even wait a bit on purpose.

Thank you very much for your help. Hopefully you will be able to test some things on macOS next.

**Comment by LiquidLemon** [comment]
I'm happy to help, I'm enjoying the theme a lot. I might be a little slow responding to issues at times though because I tend to get swamped with notifications from a work organization.
