### ISSUE TITLE
Comment mistake

### ISSUE THREAD

**Issue by JoyHak** [Naezr/ShyFox#77]
Не закрыт коммент в `shy-icons`
![Снимок экрана (12)](https://github.com/Naezr/ShyFox/assets/156242738/68434633-25aa-4727-8e19-18728ea3b359)

**Comment by Naezr** [comment]
Оно специально закоменчено ибо не доделано

**Comment by Naezr** [comment]
Но спасибо за напоминание, ты меня сподвиг таки вернуться к этим иконкам. Уже какой-то прогресс есть
![image](https://github.com/Naezr/ShyFox/assets/95460152/024e6591-75c0-423a-940b-4224431346f7)
