### ISSUE TITLE
Have to run Sidebery every time I open Firefox for the sidebar.

### ISSUE THREAD

**Issue by jasper-at-windswept** [Naezr/ShyFox#78]
I'm loving this configuration except that everytime I open Firefox I have to click on the Sidebery extension to launch it or the sidebar doesn't work.

Can this be done automatically?

**Comment by Naezr** [comment]
It's a bug in Firefox itself. Here's what I found on this problem: https://support.mozilla.org/en-US/questions/1342740

**Comment by jasper-at-windswept** [comment]
@Naezr 
That worked once for me but then the second Firefox window I opened again prompts me to open Sidebery.

**Comment by Naezr** [comment]
Are you opening a private window or a regular window? Remember that private windows cannot open the sidebar automatically. If it happens with regular windows, I can hardly help you. Try clearing your profile folder (make a backup beforehand).

**Comment by jasper-at-windswept** [comment]
Just opening a regular window. I'll create a new profile and try again.

**Comment by Naezr** [comment]
Also please note that Userchrome Toggle works pretty badly with multiple windows. You will understand when you try to toggle panels first in one window and then in another. 

In good faith I should rewrite it from scratch, because I'm having a hard time understanding the past developer's code. For now, it's staying as it is. 

Let's get back to the sidebar. If the behavior remains the same with a clean profile, then I can't help. This error has nothing to do with the theme. Look for a solution on the internet yourself

**Comment by KAGEYAM4** [comment]
@jasper-at-windswept  did it resolve? I am facing this in librewolf but not in firefox.

**Comment by KAGEYAM4** [comment]
Found it ->
https://www.reddit.com/r/firefox/comments/1eh2k5n/sidebery_open_on_firefox_startup/
https://bugzilla.mozilla.org/show_bug.cgi?id=1908019

**Comment by Naezr** [comment]
I noticed an interesting new sidabar behavior from Firefox Nightly: If you turn on a new sidabar, it will keep its state and open the same in new windows and between sessions. However, the old version does not keep its status. The old sidebar will not open automatically in new windows

**Comment by jasper-at-windswept** [comment]
@KAGEYAM4 
It did not fix the problem.

**Comment by KAGEYAM4** [comment]
@jasper-at-windswept  for me this fixes the problem -> Turn off the `History` option as shown in the screenshot. The other way is to wait for the but to be patched by firefox.


![image](https://github.com/user-attachments/assets/41cb4bf7-3fd8-4ae6-8ae6-0114b40a82d9)

**Comment by jasper-at-windswept** [comment]
@KAGEYAM4 
I already had/have history saved across windows.

**Comment by KAGEYAM4** [comment]
weird for me it works in both firefox and librewolf.
