### ISSUE TITLE
Can't see downloads

### ISSUE THREAD

**Issue by DADA30000** [Naezr/ShyFox#8]
![2024-02-06_05-53](https://github.com/Naezr/ShyFox/assets/73874445/637701d2-c3b7-4277-aa24-20e1279611e4)
![2024-02-06_05-54](https://github.com/Naezr/ShyFox/assets/73874445/b672ab8a-d4d4-48d5-b169-c5aefdf96198)

**Comment by Naezr** [comment]
didn't intend for the downloads button to be on the bottom panel, try moving it to the right panel. But I'll try to fix this bug anyway

Я смотрю ты весело проводишь время в пять утра

**Comment by Naezr** [comment]
![изображение](https://github.com/Naezr/ShyFox/assets/95460152/ed0f4a84-da68-4dc2-9116-556818457662)
I can't reproduce it. Maybe Linux has something to do with it, but it doesn't happen on Windows

**Comment by DADA30000** [comment]
> didn't intend for the downloads button to be on the bottom panel, try moving it to the right panel. But I'll try to fix this bug anyway
> 
> Я смотрю ты весело проводишь время в пять утра. Это же время там, рядом со значком Арча?

а, понятно, окей тогда
и да, это время по МСК)
