### ISSUE TITLE
Browser alerts are broken

### ISSUE THREAD

**Issue by sounak-kun** [Naezr/ShyFox#80]
First of all, amazing theme. Been using it for months, and it's genuinely the best CSS theme I've ever used.

Onto the bug, browser alerts are broken. They have been for quite some time, so it's not a regression.
![image](https://github.com/Naezr/ShyFox/assets/93094402/39d84d54-e205-4ee8-bcd2-93fee2067cea)

### Steps to reproduce:
- Open Devtools
- Type `alert("Some text here")`
- The alert will show up but there will be no text

### Platform:
Linux - Fedora 40
Gnome 46
Wayland

**Comment by sounak-kun** [comment]
Thanks for the quick response! Just pulled the update (I have it set up as a git clone, so I don't have to download all the files). A little bit of text is still cut off, but the message is easily visible now. Thanks!
![image](https://github.com/Naezr/ShyFox/assets/93094402/92b7ed8c-50a5-4594-bc52-0dc303397a05)

Glad to meet a fellow Fedora user!

**Comment by Naezr** [comment]
> A little bit of text is still cut off

The fix is already in the nightly branch. I don't think it's worth disturbing the main branch for the sake of it. It will go there as part of a bigger update
