### ISSUE TITLE
Adjust Sideberry panel size

### ISSUE THREAD

**Issue by thangisme** [Naezr/ShyFox#81]
I feel like the tab sidebar is quite large. Is there an easy way to adjust it? 
Also, I don't know if it's implemented or not, can I make the tab panel minimized (only show the tab icon but not completely hide the whole sidebar so it takes up less space) when not focus?

**Comment by Naezr** [comment]
> I feel like the tab sidebar is quite large. Is there an easy way to adjust it?

Adjust `--sdbr-wdt` in `shy-variables.css` 

> can I make the tab panel minimized (only show the tab icon but not completely hide the whole sidebar so it takes up less space) when not focus?

No, and there are no plans to do so yet. Out of the six toggles in Userchrome Toggle, only four of them are used so far. So if a lot of people want it, I could theoretically implement it. 

However, in the case of this theme, each new toggle complicates many parts several times over. For example, what to do with the bookmark bar above the sidebar? Ok, it can be left in the same row as the urlbar and only compress the sidebar. But what if the urlbar is hidden? What if the bookmarks bar is disabled? What if the window control buttons are on the left side? Every aspect needs to be thought out and considered.

So adding such a feature is possible, but very hard
