### ISSUE TITLE
Can we disable the toolbar?

### ISSUE THREAD

**Issue by Neikon** [Naezr/ShyFox#82]
I don't use the toolbar, can I disable it? I would like to have these icons in the navigation bar as well.
![imagen](https://github.com/user-attachments/assets/ea60374a-597b-49df-bb31-b47776150a46)

**Comment by Naezr** [comment]
No, you can't. But it's an interesting idea. I'll probably be able to add this in the next update.

**Comment by Naezr** [comment]
I'm closing the issue, but not giving up on the idea
