### ISSUE TITLE
Red Sidebar Button and "Open Sidebery!" notification

### ISSUE THREAD

**Issue by Neikon** [Naezr/ShyFox#83]
![imagen](https://github.com/user-attachments/assets/a43afcc1-c010-416a-b41c-d4439f4e32e6)
this is in the customization windows, and when I click in "done" sidebar button doesn't show in the navbar

I upgraded to version 3.6 and the Sidebar button was broken, is it just me?

**Comment by Naezr** [comment]
This button is only displayed when Sidebery is not open in the sidebar, signaling a problem. I recently made it display in edit mode. That's the way it's designed, just ignore it. 

I thought it would be appropriate to leave this button in edit mode, even if it doesn't display in normal situations. For example, it's needed to open the sidebar in private windows, since it doesn't do it automatically there.

However, the color is worth thinking about. Leaving it unmarked would be wrong, but the red color might confuse someone, like how you are now. If you have ideas on what to do with this button, please share them.

**Comment by Neikon** [comment]
Now I understand what you intended with this button. But I think there are scenarios where there is no error to indicate and the current behavior may not be convenient. For example, if I want to use something in the sidebar that is not sideberry will be continuously showing error messages.

![imagen](https://github.com/user-attachments/assets/c6e95139-e178-4991-89f2-4362998dc090)

For example, if I want to use something in the sidebar other than sideberry it will be continuously displaying error messages.

Maybe if you put the button in red color only for a few seconds and the message "open sideberry" would be displayed below and also only for a few seconds. We would have the warning function but without hindering the use of other elements in the sidebar.

**Comment by Neikon** [comment]
Now I understand what you intended with this button. But I think there are scenarios where there is no error to indicate and the current behavior may not be convenient. For example, if I want to use something in the sidebar that is not sideberry will be continuously showing error messages.

![imagen](https://github.com/user-attachments/assets/c6e95139-e178-4991-89f2-4362998dc090)

For example, if I want to use something in the sidebar other than sideberry it will be continuously displaying error messages.

Maybe if you put the button in red color only for a few seconds and the message "open sideberry" would be displayed below and also only for a few seconds. We would have the warning function but without hindering the use of other elements in the sidebar.

**Comment by Naezr** [comment]
As far as I know, you can't use css to make the notification only display for a few seconds. Same with the red button. 

If you want to work with bookmarks, Sidebery has functionality for that. Add a bookmarks button in Sidebery settings. 

I tried to make the "Open Sidebery!" notification disappear on hover. However, it's implemented via pseudo elements (::before and ::after) - the only way to add some element with pure css. And alas, the :hover selector doesn't work with pseudo elements.

You actually gave me an idea to redesign this notification a bit, wait for updates.

**Comment by Neikon** [comment]
Maybe with css transition elemet?

Bookmark was just an example, there are more things that people may want to use in the sidebar for a while (personally I only use sideberry there) and the current position of that message is not ideal for that use case
![imagen](https://github.com/user-attachments/assets/1a478763-f030-4590-86d8-215b206526ae)
![imagen](https://github.com/user-attachments/assets/bc1ac713-a4d7-4b6a-bb9d-3c160d01a436)

**Comment by Naezr** [comment]
> the current position of that message is not ideal for that use case

Actually this use case itself is not ideal because of the lack of tabs. I'm going to replace the notification text with "Open sidebar!". And it won't display if the sidebar is open, even if there's no Sidebery. The recommendation to open Sidebery will be located in the sidebar header. 

> Maybe with css transition elemet?

I have no idea how to do that

**Comment by Naezr** [comment]
![image](https://github.com/user-attachments/assets/5547e86a-8d11-409c-bf61-7bcd0720df7c)

It will look something like this (not the final version). Keep an eye on the nightly branch.

**Comment by Neikon** [comment]
looks good, it is a solution to the problem

**Comment by Naezr** [comment]
The possibilities for customizing Firefox are truly endless. Yes, it's still pure CSS and you can check it out in the nightly branch 

[shy-magic.webm](https://github.com/user-attachments/assets/c1afaf76-e708-4ad8-aafe-bea2c7b7a0f9)

The gist of the trick is that it's actually a "Move sidebar left/right" button. Since it doesn't serve its function anymore, I replaced the text and linked the native tabs to it.

**Comment by Naezr** [comment]
These lines can even be translated! Amazing

[shy-languages.webm](https://github.com/user-attachments/assets/aafe90f7-7193-4ed3-9651-514cbf060cd2)

**Comment by Neikon** [comment]
![imagen](https://github.com/user-attachments/assets/918944bb-53b3-468b-94ce-7dc65c78b470)
this is very cool and I like it as an alternative to the vertical tabs, but I have seen that it is buggy when you have all bars set to autohide.

**Comment by Naezr** [comment]
> buggy when you have all bars set to autohide

Can confirm on my end

> I like it as an alternative to the vertical tabs

This is not an alternative to vertical tabs, but a workaround for when Sidebery doesn't work for some reason. Tabs are overlaid on top of page, so this can be a disadvantage in many cases. 

In fact, I'm starting to run up against css limits with my ideas. For example, implementing a setting that disables the right sidebar requires inserting large identical pieces of css styles twice, with the only difference being the conditions under which they are called.

I'm thinking that this theme could grow into a full-blown Firefox-based browser at some point. If I don't give it all up, of course.

**Comment by Neikon** [comment]
Another bug It with pin tabs or they are hide or show ugly (I have 4 pin tabs)
![imagen](https://github.com/user-attachments/assets/dc8ee455-40d7-47ec-b309-32bd98c89340)
they show the last pin tab when are in full screen windows
![imagen](https://github.com/user-attachments/assets/53e5a31f-571a-4dcd-85ad-ce4e02de0179)

I encourage you to continue with the topic, even if you can't implement some ideas due to technical limitations. Now that I think about it the people behind arcfox use their own add-on to bypass the limitations https://github.com/betterbrowser/arcfox

**Comment by Naezr** [comment]
![image](https://github.com/user-attachments/assets/3deb882c-06f5-4f7c-8cd8-f2a5e3ab8d2b)
It seems the browser logic about pinned tabs has gone crazy

**Comment by Naezr** [comment]
[shy-tooltip.webm](https://github.com/user-attachments/assets/1d4095dc-57a7-4e06-befe-b7dc693def9f)
