### ISSUE TITLE
[Nightly] [Adaptive Color] Tab/toolbar background transparent if set the same slider

### ISSUE THREAD

**Issue by Neikon** [Naezr/ShyFox#87]
![imagen](https://github.com/user-attachments/assets/8e0d5078-4f8c-40dc-a508-2f6f98c86b92)
Colors become transparent if you select on the same slider level in Adaptive tab bar color

**Comment by Naezr** [comment]
If you read the README carefully, you'll find out that I've known about this issue for a long time. There is nothing you can do about it, just don't make these colors the same.
