### ISSUE TITLE
Sidebery seems to be misaligned when you drag tabs

### ISSUE THREAD

**Issue by nirurin** [Naezr/ShyFox#90]
So these pictures are the best I could manage, and while they might -appear- that the tab-drag markers are lining up with where they should be... they're actually not at all. The one that shows an arrow pointing directly in-between two tabs, is actually meant to be dropping the tab ON TOP of another tab (and if I let go, it will stack the two tabs). The entire marker system seems to be misaligned by some random amount. 

![Screenshot 2024-07-16 222632](https://github.com/user-attachments/assets/a5623ccc-1301-4355-91f7-56367ebb0f9f)
![Screenshot 2024-07-16 222621](https://github.com/user-attachments/assets/50a7a3eb-a34d-4bcc-b0d7-734ca5569534)

Edit:
As an update, I had a tinker with the shy-sidebery.css file and found that if I remove this line (pictured) entirely it seems to work as it should. I tried editing the line to other values and couldn't get it to work, but removing it didn't seem to break anything (and actually fixed the alignment problem). 

![Screenshot 2024-07-16 230131](https://github.com/user-attachments/assets/e6b8aa72-ae98-4d35-aadf-e728e2233e8a)

**Comment by Naezr** [comment]
It's a known bug, but I haven't had any luck investigating it. Thanks for your help. I will look into it and release a fix later
