### ISSUE TITLE
Request - PopUp windows (like login screens for plex and paypal) have the 'open sidebar' error message on them

### ISSUE THREAD

**Issue by nirurin** [Naezr/ShyFox#93]
When there is a login screen popup window, such as for logging into paypal or plex, it has the 'open sidebar' error message splashed onto it. 

Not a huge deal, but thought I would mention it in case there was an easy way to have it not happen for those kinds of small popup windows. 

![Screenshot 2024-07-17 174637](https://github.com/user-attachments/assets/571ebefd-542a-4a36-8c03-73ed41a16347)

**Comment by Naezr** [comment]
Most likely fixed in the nightly branch

**Comment by Naezr** [comment]
Is this issue still here?

**Comment by nirurin** [comment]
I just exchanged out the user.js and chrome folder for the ones in the nightly, and the sidebar message is still there for the login windows

**Comment by Naezr** [comment]
These popups are actually very hard to test. Do you know any site where you can call such windows? That would be helpful. I used to test this on “login with google”, but they changed the login method to a full tab.

**Comment by nirurin** [comment]
I know it happens with some PayPal payment checkouts. I have been testing
it on my overseerr setup as that uses a plex login which pops up like that.
Maybe a site which requires 2fa? As the phone code window is usually a pop
up too. Github would be my first thought.

If you can't find one I can send the link to my overseerr later, but I'd
rather dm it than write it in a public forum as its hosted on my own
server. Should work as a last resort though if none of the others work for
you.

**Comment by Naezr** [comment]
https://github.com/Naezr/ShyFox/commit/ca97fe736201fc18e3740b64716275da0aee5b6a#diff-65ba196e048edfca7814c48020b5bce5aea31953a537c6ff8cf072c733aa4aa9

That should fix the issue

**Comment by nirurin** [comment]
Tested it, worked on the overseerr window, so I'd say that's fixed now :)
