### ISSUE TITLE
SVG Extensions

### ISSUE THREAD

**Issue by Deivis44** [Naezr/ShyFox#99]
### Discussed in https://github.com/Naezr/ShyFox/discussions/98

<div type='discussions-op-text'>

<sup>Originally posted by **Deivis44** July 18, 2024</sup>
Hi, I was just trying this theme and I loved it, I have already tried some other modifications and without doubt this is the best of all, the only small detail is that I have followed to the letter the installation and configuration which is not very complex either, but the icons do not seem to apply well, I have installed “Bitwarden” and “uBlock Origin” which are supported plus I saw them inside the folder, but it seems that it does not apply I do not know due to what reason, I used to use “PotatoFox” and I was reviewing the code (https://codeberg.org/awwpotato/PotatoFox/src/branch/main/chrome/browser/icons.css) for the extensions configuration, but everything seems to be in order. Before applying the configuration on my personal user I created a test one from scratch where I did everything to the letter, but the same thing happens there as after I tried it on my user. I will share pictures of the issue and I hope you can help me :3

This was my testing profile, same happens
![image](https://github.com/user-attachments/assets/1b1bcb80-6c41-4d8f-b976-d4b83a29e9f7)

Main profile:
![image](https://github.com/user-attachments/assets/864aedca-891c-494d-a224-c7e019985b28)

-----------------------------------------------------------------------
Here are my specs:
![image](https://github.com/user-attachments/assets/c66ab0f1-05bb-46ff-9712-d55cef112a54)
</div>

**Comment by Naezr** [comment]
Did you enable `about:config` preferences for extensions icons?

**Comment by Deivis44** [comment]
> Did you enable `about:config` preferences for extensions icons?

Yes... it was that, it seems I missed that little detail, thanks, this interface you designed is great!
